#!/bin/csh -f

setenv MGIDIR		/usr/local/mgi/build34

setenv MIGRATIONDIR	/home/lec/db/mgidbmigration/BUILD34

setenv ENTREZGENELOAD	${MGIDIR}/dataload/entrezgeneload
setenv MRKCACHELOAD	${MGIDIR}/dataload/mrkcacheload
setenv SEQCACHELOAD	${MGIDIR}/dataload/seqcacheload

setenv mgddb ${MGIDIR}/dbutils/mgd
setenv mgddbschema ${mgddb}/mgddbschema

setenv radardb ${MGIDIR}/dbutils/radar
setenv radardbschema ${radardb}/radardbschema

source ${radardbschema}/Configuration
setenv RADARDB $DBNAME

source ${mgddbschema}/Configuration

