#!/bin/csh -f

#setenv MGIDIR		/usr/local/mgi/live
setenv MGIDIR		/usr/local/mgi/build34

setenv BUILD34		/mgi/all/wts_projects/6800/6832/data

setenv ASSEMBLYSEQLOAD	${MGIDIR}/dataload/assemblyseqload
setenv EGLOAD		${MGIDIR}/dataload/egload
setenv ENTREZGENELOAD	${MGIDIR}/dataload/entrezgeneload
setenv MRKCACHELOAD	${MGIDIR}/dataload/mrkcacheload
setenv SEQCACHELOAD	${MGIDIR}/dataload/seqcacheload

setenv mgddb ${MGIDIR}/dbutils/mgd
setenv mgddbschema ${mgddb}/mgddbschema

setenv radardb ${MGIDIR}/dbutils/radar
setenv radardbschema ${radardb}/radardbschema

source ${radardbschema}/Configuration
setenv RADARDB $DBNAME

source ${mgddbschema}/Configuration

