#!/bin/csh -f

#setenv MIGRATIONDIR	/usr/local/mgi/live/dbutils/mgidbmigration/MGI3.41
setenv MIGRATIONDIR	/home/lec/db/mgidbmigration/MGI3.41

#setenv newmgddb /usr/local/mgi/live/dbutils/mgd
setenv newmgddb /home/lec/db/mgi3.41
setenv newmgddbschema ${newmgddb}/mgddbschema
setenv newmgddbperms ${newmgddb}/mgddbperms

source ${newmgddbschema}/Configuration

