#!/bin/csh -f

setenv DBUTILITIESDIR	/usr/local/mgi/dbutils/mgidbutilities
setenv PYTHONPATH       /usr/local/mgi/lib/python

setenv LABELLOAD /usr/local/mgi/dbutils/mrklabelload
#setenv LIBLOAD /usr/local/mgi/dataload/libraryload
setenv LIBLOAD /home/lec/loads/libraryload

#setenv newmgddb /usr/local/mgi/dbutils/mgd
setenv newmgddb /home/lec/db
setenv newmgddbschema ${newmgddb}/mgddbschema
setenv newmgddbperms ${newmgddb}/mgddbperms

#setenv newnomendb //usr/local/mgi/dbutils/nomen
setenv newnomendb /home/lec/db
setenv newnomendbschema ${newmgddb}/nomendbschema
setenv newnomendbperms ${newmgddb}/nomendbperms

setenv NOMEN nomen_release

source ${newmgddbschema}/Configuration

