#!/bin/csh -f

setenv MIGRATIONDIR	/usr/local/mgi/live/dbutils/mgidbmigration/MGI3.43

setenv newmgddb /usr/local/mgi/live/dbutils/mgd
setenv newmgddbschema ${newmgddb}/mgddbschema
setenv newmgddbperms ${newmgddb}/mgddbperms

setenv newradardb /usr/local/mgi/live/dbutils/radar
setenv newradardbschema ${newradardb}/radardbschema
setenv newradardbperms ${newradardb}/radardbperms

setenv SCHEMA_TAG       mgddbschema-3-4-0
setenv CREATEDBY	1000
setenv PUBLIC_VERSION   "MGI 3.43"

source ${newradardbschema}/Configuration
setenv RADARDB	${DBNAME}

source ${newmgddbschema}/Configuration

