#!/bin/csh -f

#setenv TRANSLOAD        /usr/local/mgi/3.0/dataload/translationload
setenv TRANSLOAD        /home/lec/loads/translationload
#setenv SETLOAD		/usr/local/mgi/3.0/dataload/setload
setenv SETLOAD		/home/lec/loads/setload
setenv RADARDBUTILS	/usr/local/mgi/3.0/dbutils/radardbutilities

# use current MGI 2.98 version of vocload because we load
# the vocabularies BEFORE converting to the new schema
setenv VOCLOAD          /home/lec/loads/vocload-2.98/runSimpleFullLoadNoArchive.sh
# load provider AFTER conversion because descriptions won't fit
setenv NEWVOCLOAD       /home/lec/loads/vocload/runSimpleFullLoadNoArchive.sh

# existing (MGI 2.98) schema configured to talk to an MGI 2.98 database
setenv existingmgddbschema /home/lec/db/mgi2.98/mgddbschema

# existing (MGI 2.98) schema configured to talk to the JSAM database
setenv oldmgddb /home/lec/db/jsam2.98
setenv oldmgddbschema ${oldmgddb}/mgddbschema
setenv oldmgddbperms ${oldmgddb}/mgddbperms

# new (JSAM) schema configured to talk to the JSAM database
setenv newmgddb /home/lec/db
setenv newmgddbschema ${newmgddb}/mgddbschema
setenv newmgddbperms ${newmgddb}/mgddbperms

# new (JSAM) RADAR schema configured to talk to JSAM RADAR database
setenv newrdrdb /home/lec/db
setenv newrdrdbschema ${newrdrdb}/radardbschema
setenv newrdrdbperms ${newrdrdb}/radardbperms

# the working directory
setenv WORKDIR  /extra1/sybase

# the backup directory
setenv BACKUPDIR  /extra2/sybase

# the path where the bcp files have been installed
setenv DATADIR  ${WORKDIR}/data

setenv CREATEDBY	1300
setenv UNKNOWNEDITOR	1211
setenv SCHEMA_TAG	mgddbschema-8-0-0
setenv PUBLIC_VERSION	"MGI 3.0"
setenv PRODUCT_NAME	MGD
setenv RADAR_SCHEMA_TAG	radardbschema-2-0-0

source ${newmgddbschema}/Configuration

