#!/bin/csh -f

#setenv MIGRATIONDIR	/usr/local/mgi/3.3/dbutils/mgidbmigration/MPR
setenv MIGRATIONDIR	/home/lec/db/mgidbmigration/MGI3.3

#setenv MRKCACHELOAD	/usr/local/mgi/3.3/dataload/mrkcacheload
setenv MRKCACHELOAD	/home/lec/loads/mrkcacheload

#setenv SEQCACHELOAD	/usr/local/mgi/3.3/dataload/seqcacheload
setenv SEQCACHELOAD	/home/lec/loads/seqcacheload

setenv VOCSIMPLELOAD    /usr/local/mgi/live/dataload/vocload/runSimpleFullLoadNoArchive.sh
#setenv VOCDAGLOAD    	/usr/local/mgi/live/dataload/vocload/runDAGIncLoad.sh
setenv VOCDAGLOAD    	/home/lec/loads/vocload/runDAGIncLoad.sh

setenv IMGDIRECTORY	${MIGRATIONDIR}/mlcjpegs
setenv PIXELDBDATA	/usr/local/mgi/pixeldb_data
#setenv PIXELDBDATA	/usr/local/mgi/live/pixeldb_data
setenv PIXELDBCOUNTER   ${PIXELDBDATA}/accession/counter
setenv IMGLOADDATADIR   ${MIGRATIONDIR}

#setenv newmgddb /usr/local/mgi/3.3/dbutils/mgd
setenv oldmgddb /home/lec/db/live
setenv newmgddb /home/lec/db/live
setenv oldmgddbschema ${oldmgddb}/mgddbschema-3-2-2-7
setenv newmgddbschema ${newmgddb}/mgddbschema
setenv newmgddbperms ${newmgddb}/mgddbperms

setenv SCHEMA_TAG       mgddbschema-3-3-0
setenv CREATEDBY	1000
setenv PUBLIC_VERSION   "MGI 3.3"

source ${newmgddbschema}/Configuration

