#!/bin/csh -f

#
#
#

cd `dirname $0` && source ./Configuration

setenv LOG $0.log
rm -rf ${LOG}
touch ${LOG}
 
date | tee -a ${LOG}

echo "Drop Indexes..." | tee -a ${LOG}
 
cat - <<EOSQL | doisql.csh $0 | tee -a ${LOG}

drop index ACC_AccessionMax.idx_modification_date
drop index ACC_ActualDB.idx_modification_date
drop index ACC_LogicalDB.idx_modification_date
drop index ACC_MGIType.idx_modification_date
drop index ALL_Allele.idx_modification_date
drop index ALL_Allele_Mutation.idx_modification_date
drop index ALL_CellLine.idx_modification_date
drop index BIB_Books.idx_modification_date
drop index BIB_Notes.idx_modification_date
drop index BIB_Refs.idx_modification_date
drop index BIB_ReviewStatus.idx_modification_date
drop index CRS_Cross.idx_modification_date
drop index CRS_Matrix.idx_modification_date
drop index CRS_Progeny.idx_modification_date
drop index CRS_References.idx_modification_date
drop index CRS_Typings.idx_modification_date
drop index DAG_Closure.idx_modification_date
drop index DAG_DAG.idx_modification_date
drop index DAG_Edge.idx_modification_date
drop index DAG_Label.idx_modification_date
drop index DAG_Node.idx_modification_date
drop index GXD_AlleleGenotype.idx_modification_date
drop index GXD_AllelePair.idx_modification_date
drop index GXD_Antibody.idx_modification_date
drop index GXD_AntibodyAlias.idx_modification_date
drop index GXD_AntibodyClass.idx_modification_date
drop index GXD_AntibodyMarker.idx_modification_date
drop index GXD_AntibodyPrep.idx_modification_date
drop index GXD_AntibodyType.idx_modification_date
drop index GXD_Antigen.idx_modification_date
drop index GXD_Assay.idx_modification_date
drop index GXD_AssayNote.idx_modification_date
drop index GXD_AssayType.idx_modification_date
drop index GXD_EmbeddingMethod.idx_modification_date
drop index GXD_FixationMethod.idx_modification_date
drop index GXD_GelBand.idx_modification_date
drop index GXD_GelControl.idx_modification_date
drop index GXD_GelLane.idx_modification_date
drop index GXD_GelLaneStructure.idx_modification_date
drop index GXD_GelRNAType.idx_modification_date
drop index GXD_GelRow.idx_modification_date
drop index GXD_GelUnits.idx_modification_date
drop index GXD_Genotype.idx_modification_date
drop index GXD_Index.idx_modification_date
drop index GXD_Index_Stages.idx_modification_date
drop index GXD_InSituResult.idx_modification_date
drop index GXD_InSituResultImage.idx_modification_date
drop index GXD_ISResultStructure.idx_modification_date
drop index GXD_Label.idx_modification_date
drop index GXD_LabelCoverage.idx_modification_date
drop index GXD_Pattern.idx_modification_date
drop index GXD_ProbePrep.idx_modification_date
drop index GXD_ProbeSense.idx_modification_date
drop index GXD_Secondary.idx_modification_date
drop index GXD_Specimen.idx_modification_date
drop index GXD_Strength.idx_modification_date
drop index GXD_Structure.idx_modification_date
drop index GXD_StructureClosure.idx_modification_date
drop index GXD_StructureName.idx_modification_date
drop index GXD_TheilerStage.idx_modification_date
drop index GXD_VisualizationMethod.idx_modification_date
drop index HMD_Assay.idx_modification_date
drop index HMD_Class.idx_modification_date
drop index HMD_Homology_Assay.idx_modification_date
drop index HMD_Homology.idx_modification_date
drop index HMD_Homology_Marker.idx_modification_date
drop index HMD_Notes.idx_modification_date
drop index IMG_ImagePane.idx_modification_date
drop index MAP_Coord_Collection.idx_modification_date
drop index MAP_Coord_Feature.idx_modification_date
drop index MAP_Coordinate.idx_modification_date
drop index MGI_AttributeHistory.idx_modification_date
drop index MGI_Columns.idx_modification_date
drop index MGI_Note.idx_modification_date
drop index MGI_NoteChunk.idx_modification_date
drop index MGI_NoteType.idx_modification_date
drop index MGI_Organism.idx_modification_date
drop index MGI_Organism_MGIType.idx_modification_date
drop index MGI_RefAssocType.idx_modification_date
drop index MGI_Reference_Assoc.idx_modification_date
drop index MGI_RoleTask.idx_modification_date
drop index MGI_Set.index_modification_date
drop index MGI_SetMember.index_modification_date
drop index MGI_Tables.idx_modification_date
drop index MGI_Translation.idx_modification_date
drop index MGI_TranslationType.idx_modification_date
drop index MGI_User.idx_modification_date
drop index MGI_UserRole.idx_modification_date
drop index MGI_VocAssociation.idx_modification_date
drop index MGI_VocAssociationType.idx_modification_date
drop index MLC_Marker.idx_modification_date
drop index MLC_Reference.idx_modification_date
drop index MLC_Text.idx_modification_date
drop index MLD_Assay_Types.idx_modification_date
drop index MLD_Concordance.idx_modification_date
drop index MLD_Contig.idx_modification_date
drop index MLD_ContigProbe.idx_modification_date
drop index MLD_Distance.idx_modification_date
drop index MLD_Expt_Marker.idx_modification_date
drop index MLD_Expt_Notes.idx_modification_date
drop index MLD_Expts.idx_modification_date
drop index MLD_FISH.idx_modification_date
drop index MLD_FISH_Region.idx_modification_date
drop index MLD_Hit.idx_modification_date
drop index MLD_Hybrid.idx_modification_date
drop index MLD_InSitu.idx_modification_date
drop index MLD_ISRegion.idx_modification_date
drop index MLD_Marker.idx_modification_date
drop index MLD_Matrix.idx_modification_date
drop index MLD_MC2point.idx_modification_date
drop index MLD_MCDataList.idx_modification_date
drop index MLD_Notes.idx_modification_date
drop index MLD_PhysMap.idx_modification_date
drop index MLD_RI2Point.idx_modification_date
drop index MLD_RI.idx_modification_date
drop index MLD_RIData.idx_modification_date
drop index MLD_Statistics.idx_modification_date
drop index MRK_Alias.idx_modification_date
drop index MRK_Anchors.idx_modification_date
drop index MRK_Chromosome.idx_modification_date
drop index MRK_Class.idx_modification_date
drop index MRK_Classes.idx_modification_date
drop index MRK_Current.idx_modification_date
drop index MRK_Event.idx_modification_date
drop index MRK_EventReason.idx_modification_date
drop index MRK_History.idx_modification_date
drop index MRK_Marker.idx_modification_date
drop index MRK_Notes.idx_modification_date
drop index MRK_Offset.idx_modification_date
drop index MRK_Reference.idx_modification_date
drop index MRK_Status.idx_modification_date
drop index MRK_Types.idx_modification_date
drop index NOM_Marker.idx_modification_date
drop index PRB_Alias.idx_modification_date
drop index PRB_Allele.idx_modification_date
drop index PRB_Allele_Strain.idx_modification_date
drop index PRB_Marker.idx_modification_date
drop index PRB_Notes.idx_modification_date
drop index PRB_Probe.idx_modification_date
drop index PRB_Ref_Notes.idx_modification_date
drop index PRB_Reference.idx_modification_date
drop index PRB_RFLV.idx_modification_date
drop index PRB_Source.idx_modification_date
drop index PRB_Strain.idx_modification_date
drop index PRB_Strain_Genotype.index_modification_date
drop index PRB_Strain_Marker.index_modification_date
drop index PRB_Strain_Type.idx_modification_date
drop index PRB_Tissue.idx_modification_date
drop index RI_RISet.idx_modification_date
drop index SEQ_Source_Assoc.idx_modification_date
drop index SEQ_Source_Assoc.idx_modification_date
drop index VOC_Annot.idx_modification_date
drop index VOC_AnnotHeader.idx_modification_date
drop index VOC_AnnotType.idx_modification_date
drop index VOC_Evidence.idx_modification_date
drop index VOC_Term.idx_modification_date
drop index VOC_Text.idx_modification_date
drop index VOC_Vocab.idx_modification_date
drop index VOC_VocabDAG.idx_modification_date
drop index WKS_Rosetta.index_modification_date
drop index ALL_Allele.idx_creation_date
drop index BIB_ReviewStatus.idx_creation_date
drop index MGI_Columns.idx_creation_date
drop index MGI_Tables.idx_creation_date
go

checkpoint
go

EOSQL

date | tee -a $LOG

