#!/bin/csh -f

setenv MIGRATIONDIR	/usr/local/mgi/live/dbutils/mgidbmigration/SNP

setenv EGLOAD  /usr/local/mgi/live/dataload/entrezgeneload

setenv SEQCACHELOAD	/usr/local/mgi/live/dbutils/seqcacheload

setenv MRKCACHELOAD	/usr/local/mgi/live/dbutils/mrkcacheload

setenv ORTHOLOAD	/usr/local/mgi/live/dataload/orthologyload

setenv NOTELOAD         /usr/local/mgi/live/dataload/noteload/mginoteload.py

setenve PIRSFLOAD     /usr/local/mgi/live/dataload/pirsfload/bin/pirsfload.sh

setenv newmgddb /usr/local/mgi/live/dbutils/mgd
setenv newmgddbschema ${newmgddb}/mgddbschema
setenv newmgddbperms ${newmgddb}/mgddbperms

setenv newradardb /usr/local/mgi/live/dbutils/radar
setenv newradardbschema ${newradardb}/radardbschema
setenv newradardbperms ${newradardb}/radardbperms

setenv SCHEMA_TAG       mgddbschema-3-4-0
setenv CREATEDBY	1000
setenv PUBLIC_VERSION   "MGI 3.4"

source ${newradardbschema}/Configuration
setenv RADARDB	${DBNAME}

source ${newmgddbschema}/Configuration

