#!/bin/csh -f

#setenv MIGRATIONDIR	/usr/local/mgi/live/dbutils/mgidbmigration/SNP
setenv MIGRATIONDIR	/home/sc/snp/mgidbmigration/SNP

setenv EGLOAD   /home/lec/loads/entrezgeneload-pirsf
#setenv EGLOAD  /usr/local/mgi/live/dataload/entrezgeneload

setenv SEQCACHELOAD	/home/lec/loads/seqcacheload-pirsf
#setenv SEQCACHELOAD	/usr/local/mgi/live/dbutils/seqcacheload

setenv DBSNPLOAD	/home/sc/snp/dbsnpload/bin/dbsnpload.sh
#setenv DBSNPLOAD	/usr/local/mgi/live/dataload/dbsnpload/bin/dbsnpload.sh

setenv ORTHOLOAD	/home/lec/loads/orthologyload
#setenv ORTHOLOAD	/usr/local/mgi/live/dataload/orthologyload

setenv PIRSFLOAD       /home/mbw/sandbox/pirsfload/bin/pirsfload.sh
#setenve PIRSFLOAD     /usr/local/mgi/live/dataload/pirsfload/bin/pirsfload.sh

#setenv newmgddb /usr/local/mgi/live/dbutils/mgd
setenv newmgddb /home/sc/snp
setenv newmgddbschema ${newmgddb}/mgddbschema-snp
setenv newmgddbperms ${newmgddb}/mgddbperms-snp

#setenv newradardb /usr/local/mgi/live/dbutils/radar
setenv newradardb /home/sc/snp
setenv newradardbschema ${newradardb}/radardbschema-snp
setenv newradardbperms ${newradardb}/radardbperms-snp

setenv SCHEMA_TAG       mgddbschema-3-4-0
setenv CREATEDBY	1000
setenv PUBLIC_VERSION   "MGI 3.4"

source ${newradardbschema}/Configuration
setenv RADARDB	${DBNAME}

source ${newmgddbschema}/Configuration

