#!/usr/local/bin/python

import sys
import string
import mgdlib

def debug(s):
	sys.stderr.write( s + '\n')

if len(sys.argv) != 5:
	debug("Usage: %s <server> <database> <user> <password file>" % sys.argv[0] )

server = sys.argv[1]
database = sys.argv[2]
user = sys.argv[3]
passwordfile = sys.argv[4]

fd = open( passwordfile, 'r' )
password = string.strip( fd.readline() )
fd.close()

mgdlib.set_sqlLogin( user, password, server, database)

cmd = '''
	select _Refs_key
	from BIB_View
	where jnum = 46439
	'''
debug(cmd)
res = mgdlib.sql( cmd, 'auto' )
_Refs_key = res[0]['_Refs_key']

#
# Save keys of probes used in assays. Can't delete probes first because
# they are referenced by assays. But after we delete assays, don't
# know which probes to delete.
#

try:
    mgdlib.sql("drop table tempdb..PRB_keys", 'auto')
except:
    pass

cmd = '''
	select pp._Probe_key
	into tempdb..PRB_keys
	from PRB_Probe pp, GXD_ProbePrep gp, GXD_Assay ga
	where pp._Probe_key = gp._Probe_key
	and gp._ProbePrep_key = ga._ProbePrep_key
	and ga._Refs_key = %d
    ''' % _Refs_key
debug(cmd)
mgdlib.sql(cmd, 'auto')

cmd = '''
	delete from GXD_Assay
	where _Refs_key = %d
	''' % _Refs_key
debug(cmd)
mgdlib.sql(cmd, 'auto')

cmd = '''
	delete from IMG_Image
	where _Refs_key = %d
	''' % _Refs_key
debug(cmd)
mgdlib.sql(cmd, 'auto')

cmd = '''
	delete
	from PRB_Probe 
	where _Probe_key in (select _Probe_key from tempdb..PRB_keys)
	'''
debug(cmd)
mgdlib.sql(cmd, 'auto')

try:
    mgdlib.sql("drop table tempdb..PRB_keys", 'auto')
except:
    pass
