#!/usr/local/bin/python

import sys
import string
import os
import posix
import mgdlib

if len(sys.argv) != 5:
	print "usage: %s server database user passwdfile" % sys.argv[0]
	sys.exit(-1)

server = sys.argv[1]
database = sys.argv[2]
user = sys.argv[3]
passwdFile = sys.argv[4]
try:
	fd =  open(passwdFile, 'r')
	password = string.strip( fd.readline() )
	fd.close()
except:
	print "Could not read password."
	sys.exit(-1)

mgdlib.set_sqlLogin( user, password, server, database )

bcps = [ ]
for fn in posix.listdir("."):
	if string.find( fn, ".bcp") != -1:
		bcps.append( fn )
bcps.sort()

for fn in bcps:
	tn = fn[:string.find( fn, '.')]
	efn = tn + ".err"
	posix.system('rm %s' % efn)

	cmd = '$SYBASE/bin/bcp %s..%s in %s -S %s -U %s -P %s -c -e %s' \
			% (database, tn, fn, server, user, password, efn)
	print cmd
	os.system(cmd)

