#!/bin/csh -f

setenv MIGRATIONDIR	/home/lec/db/mgidbmigration/TR6520

#setenv VOCLOAD          /usr/local/mgi/live/dataload/vocload/runSimpleFullLoadNoArchive.sh
setenv VOCLOAD          /home/lec/loads/vocload/runSimpleFullLoadNoArchive.sh

# new schema configured to talk to the TR 6520 database

#setenv newmgddb /usr/local/mgi/live/dbutils/mgd
setenv newmgddb /home/lec/db
setenv newmgddbschema ${newmgddb}/mgddbschema
setenv newmgddbperms ${newmgddb}/mgddbperms

setenv SCHEMA_TAG       mgddbschema-3-1-1

source ${newmgddbschema}/Configuration

