#!/bin/csh -f

# Production settings
#
#setenv MGDDBSCHEMA	/usr/local/mgi/live/dbutils/mgd/mgddbschema
#setenv RADARDBSCHEMA	/usr/local/mgi/live/dbutils/radar/radardbschema
#setenv RADARDBPERMS	/usr/local/mgi/live/dbutils/radar/radardbperms

# Development settings
#
setenv MGDDBSCHEMA	/home/dbm/mgi/dbutils/mgd/mgddbschema
setenv RADARDBSCHEMA	/home/dbm/mgi/dbutils/radar/radardbschema
setenv RADARDBPERMS	/home/dbm/mgi/dbutils/radar/radardbperms

setenv CREATEDBY	1000
