#!/bin/csh -f

#setenv MIGRATIONDIR	/usr/local/mgi/live/dbutils/mgidbmigration/MGI3.5
setenv MIGRATIONDIR	/home/lec/db/mgidbmigration/MGI3.5

#setenv OMIMCACHELOAD	/usr/local/mgi/live/dbutils/mrkcacheload/mrkomim.csh
setenv OMIMCACHELOAD	/home/lec/loads/mrkcacheload-tr7062/mrkomim.csh

#setenv newmgddb /usr/local/mgi/live/dbutils/mgd
setenv newmgddb /home/lec/db/mgi3.5
setenv newmgddbschema ${newmgddb}/mgddbschema
setenv newmgddbperms ${newmgddb}/mgddbperms

setenv SCHEMA_TAG       mgddbschema-3-5-0
setenv CREATEDBY	1000

source ${newmgddbschema}/Configuration

