#!/bin/csh -f

#
# migrates bib_refs._referencetype_key
#


if ( ${?MGICONFIG} == 0 ) then
        setenv MGICONFIG /usr/local/mgi/live/mgiconfig
endif

source ${MGICONFIG}/master.config.csh

cd `dirname $0`

setenv LOG $0.log
rm -rf $LOG
touch $LOG
 
date | tee -a $LOG

cat - <<EOSQL | ${PG_DBUTILS}/bin/doisql.csh $0 | tee -a $LOG

update BIB_Refs r
set _ReferenceType_key = (select t._Term_key
        from VOC_Vocab v, VOC_Term t
        where v.name = 'Reference Type' and v._Vocab_key = t._Vocab_key 
        and t.term = 'Peer Reviewed Article')
where r.journal in (
'Am J Hum Genet',
'Anat Rec',
'Anim Genet',
'Arch Physiol Biochem',
'Behav Genet',
'Blood',
'Br J Rheumatol',
'Brain Pathol',
'Circulation',
'Cong Anom',
'Cytogenet Cell Genet',
'Dev Dyn',
'Diabetes',
'Eur Cytokine Netw',
'Exp Hematol',
'Experientia',
'FASEB J',
'Fed Proc',
'Gastroenterology',
'Genet Res',
'Genetics',
'Genome',
'Hepatology',
'Hered Deaf News',
'Hereditas',
'Hum Reprod',
'Immunogenetics',
'Int J Exp Pathol',
'Invest Ophthalmol Vis Sci',
'Isozyme Bulletin',
'J Anat',
'J Anim Sci',
'J Assist Reprod Genet',
'J Bone Miner Res',
'J Exp Zool',
'J Immunol',
'J Invest Dermatol',
'J Neurochem',
'J Neuropathol Exp Neurol',
'J Pathol',
'J Physiol',
'J Reprod Fertil',
'J Reticuloendothel Soc',
'Lab Invest',
'Mamm Genome',
'Mol Immunol',
'Neuropathology',
'Neurosci Lett',
'Neuroscience',
'Proc Am Assoc Cancer Res',
'Prostaglandins',
'Regul Pept',
'Sleep',
'Soc Neurosci',
'Teratology',
'Tex Rep Biol Med',
'Trans R Soc Trop Med Hyg',
'Transgenic Res',
'Res Rep Health Eff Inst',
'Acad J Xian Jiaotong Univ',
'ACS Chem Neurosci',
'Acta',
'Acta Anat (Basel)',
'Acta Biochim Biophys Sin (Shanghai)',
'Acta Biochim Pol',
'Acta Biol Acad Sci Hung',
'Acta Biol Hung',
'Acta Biol Med Ger',
'Acta Cir Bras',
'Acta Crystallogr D Biol Crystallogr',
'Acta Crystallogr Sect F Struct Biol Cryst Commun',
'Acta Derm Venereol',
'Acta Diabetol',
'Acta Endocrinol (Copenh)',
'Acta Genet Med Gemellol (Roma)',
'Acta Haematol',
'Acta Histochem',
'Acta Histochem Cytochem',
'Acta Leprol',
'Acta Med Okayama',
'Acta Microbiol Acad Sci Hung',
'Acta Microbiol Hung',
'Acta Neurchir (Wien)',
'Acta Neuropathol',
'Acta Neuropathol (Berl)',
'Acta Neuropathol Commun',
'Acta Odontol Latinoam',
'Acta Odontol Scand',
'Acta Oncol',
'Acta Otolaryngol',
'Acta Otolaryngol (Stockh)',
'Acta Otolaryngol Suppl',
'Acta Otolaryngol Suppl (Stockh)',
'Acta Paediatr',
'Acta Paediatr Suppl',
'Acta Pathol Jpn',
'Acta Pathol Microbiol Scand',
'Acta Pathol Microbiol Scand [A]',
'Acta Pathol Microbiol Scand B Microbiol Immunol',
'Acta Pharmacol Sin',
'Acta Physiol (Oxf)',
'Acta Physiol Lat Am',
'Acta Physiol Scand',
'Acta Trop',
'Acta Union Int Contre Cancer',
'Acta Univ Palacki Olomuc Fac Med',
'Acta Vet Scand',
'Acta Virol',
'Addict Biol',
'Adipocyte',
'Adv Anat Embryol Cell Biol',
'Adv Cancer Res',
'Adv Dent Res',
'Adv Dev Biol',
'Adv Drug Del Rev',
'Adv Drug Deliv Rev',
'Adv Enzyme Regul',
'Adv Exp Med Biol',
'Adv Genet',
'Adv Genomics Genet',
'Adv Immunol',
'Adv Neuroimmunol',
'Adv Neurol',
'Adv Otorhinolaryngol',
'Adv Pharmacol',
'Adv Prostaglandin Thromboxane Leukot Res',
'Adv Second Messenger Phosphoprotein Res',
'Adv Space Res',
'Adv Vet Sci Comp Med',
'Adv Wound Care (New Rochelle)',
'Age',
'Age (Dordr)',
'Ageing Res Rev',
'Agents Actions',
'Aggress Behav',
'Aging (Albany NY)',
'Aging Cell',
'Aging Dis',
'AIDS',
'AIDS Res Hum Retroviruses',
'AJNR Am J Neuroradiol',
'Alcohol',
'Alcohol Alcohol',
'Alcohol Alcohol Suppl',
'Alcohol Clin Exp Res',
'Alcohol Res Health',
'Aliment Pharmacol Ther',
'Allergol Int',
'Allergy',
'Alzheimers Res Ther',
'Am J Physiol Cell Physiol',
'Am Naturalist',
'Ann Hum Genet',
'Biochem Biophys Res Commun',
'Biochem J',
'Biochim Biophys Acta',
'Biol Open',
'Biol Reprod',
'Biotechniques',
'BMC Evol Biol',
'BMC Genet',
'BMC Genomics',
'BMC Res Notes',
'Breast Cancer Res',
'Cancer Res',
'Cell',
'Cell Rep',
'Cell Stem Cell',
'Chinese Science Bulletin',
'Dev Biol',
'Dev Cell',
'Dev Genet',
'DNA Res',
'Drug Discov Today',
'EMBO J',
'EMBO Mol Med',
'Endocrinology',
'Evolution',
'Exp Brain Res',
'Exp Mol Pathol',
'F1000Research',
'FEBS Lett',
'Fertil Steril',
'Front Mol Neurosci',
'Front Synaptic Neurosci',
'Gamete Res',
'Genes Cells',
'Genes Immun',
'Genesis',
'Genetica',
'Genetica Polonica',
'Genome Res',
'Genomics',
'Heredity',
'Hum Mol Genet',
'Int J Dev Biol',
'J Am Heart Assoc',
'J Biol Chem',
'J Biomed Semantics',
'J Craniofac Genet Dev Biol',
'J Endocrinol',
'J Exp Med',
'J Genet',
'J Hered',
'J Inorg Biochem',
'J Morphol',
'J Natl Cancer Inst',
'J Neurosci',
'J Steroid Biochem Mol Biol',
'JCI Insight',
'Leukemia',
'Mol Biol Cell',
'Mol Cell',
'Mol Cell Biochem',
'Mol Cell Biol',
'Mol Vis',
'Nat Biotechnol',
'Nat Genet',
'Nat Methods',
'Nat Neurosci',
'Nature',
'Neurobiol Aging',
'Neurobiol Dis',
'Neuron',
'Nucleic Acids Res',
'Oncogene',
'Open Biol',
'Pflugers Arch',
'Pigment Cell Res',
'PLoS Genet',
'PLoS One',
'Proc Natl Acad Sci U S A',
'Sci Rep',
'Sci Transl Med',
'Science',
'Semin Reprod Med',
'Theor Appl Genet',
'Toxicol Appl Pharmacol',
'Toxins (Basel)',
'Acad J Xian Jiaotong Univ',
'ACS Chem Neurosci',
'Acta',
'Acta Anat (Basel)',
'Acta Biochim Biophys Sin (Shanghai)',
'Acta Biochim Pol',
'Acta Biol Acad Sci Hung',
'Acta Biol Hung',
'Acta Biol Med Ger',
'Acta Cir Bras',
'Acta Crystallogr D Biol Crystallogr',
'Acta Crystallogr Sect F Struct Biol Cryst Commun',
'Acta Derm Venereol',
'Acta Diabetol',
'Acta Endocrinol (Copenh)',
'Acta Genet Med Gemellol (Roma)',
'Acta Haematol',
'Acta Histochem',
'Acta Histochem Cytochem',
'Acta Leprol',
'Acta Med Okayama',
'Acta Microbiol Acad Sci Hung',
'Acta Microbiol Hung',
'Acta Neurchir (Wien)',
'Acta Neuropathol',
'Acta Neuropathol (Berl)',
'Acta Neuropathol Commun',
'Acta Odontol Latinoam',
'Acta Odontol Scand',
'Acta Oncol',
'Acta Otolaryngol',
'Acta Otolaryngol (Stockh)',
'Acta Otolaryngol Suppl (Stockh)',
'Acta Paediatr',
'Acta Paediatr Suppl',
'Acta Pathol Jpn',
'Acta Pathol Microbiol Scand',
'Acta Pathol Microbiol Scand [A]',
'Acta Pathol Microbiol Scand B Microbiol Immunol',
'Acta Pharmacol Sin',
'Acta Physiol (Oxf)',
'Acta Physiol Lat Am',
'Acta Physiol Scand',
'Acta Trop',
'Acta Union Int Contre Cancer',
'Acta Univ Palacki Olomuc Fac Med',
'Acta Vet Scand',
'Acta Virol',
'Addict Biol',
'Adipocyte',
'Adv Anat Embryol Cell Biol',
'Adv Cancer Res',
'Adv Dent Res',
'Adv Dev Biol',
'Adv Drug Del Rev',
'Adv Drug Deliv Rev',
'Adv Enzyme Regul',
'Adv Genet',
'Adv Genomics Genet',
'Adv Immunol',
'Adv Neuroimmunol',
'Adv Neurol',
'Adv Otorhinolaryngol',
'Adv Pharmacol',
'Adv Prostaglandin Thromboxane Leukot Res',
'Adv Second Messenger Phosphoprotein Res',
'Adv Space Res',
'Adv Vet Sci Comp Med',
'Adv Wound Care (New Rochelle)',
'Age',
'Age (Dordr)',
'Ageing Res Rev',
'Agents Actions',
'Aging (Albany NY)',
'Aging Cell',
'Aging Dis',
'AIDS',
'AIDS Res Hum Retroviruses',
'AJNR Am J Neuroradiol',
'Alcohol',
'Alcohol Alcohol',
'Alcohol Alcohol Suppl',
'Alcohol Clin Exp Res',
'Alcohol Res Health',
'Aliment Pharmacol Ther',
'Allergol Int',
'Allergy',
'Alzheimers Res Ther',
'Am J Addict',
'Am J Anat',
'Am J Cancer',
'Am J Cardiol',
'Am J Chin Med',
'Am J Clin Nutr',
'Am J Clin Oncol',
'Am J Clin Pathol',
'Am J Dermatopathol',
'Am J Hematol',
'Am J Hum Biol',
'Am J Hygiene',
'Am J Hypertens',
'Am J Ind Med',
'Am J Kidney Dis',
'Am J Med Genet',
'Am J Med Genet A',
'Am J Med Genet B Neuropsychiatr Genet',
'Am J Med Sci',
'Am J Nephrol',
'Am J Obstet Gynecol',
'Am J Ophthalmol',
'Am J Orthod Dentofacial Orthop',
'Am J Otolaryngol',
'Am J Pathol',
'Am J Pediatr Hematol Oncol',
'Am J Pharmacogenomics',
'Am J Phys Anthropol',
'Am J Physiol',
'Am J Physiol Endocrinol Metab',
'Am J Physiol Gastrointest Liver Physiol',
'Am J Physiol Heart Circ Physiol',
'Am J Physiol Lung Cell Mol Physiol',
'Am J Physiol Regul Integr Comp Physiol',
'Am J Physiol Renal Physiol',
'Am J Primatol',
'Am J Psychiatry',
'Am J Reprod Immunol',
'Am J Respir Cell Mol Biol',
'Am J Respir Crit Care Med',
'Am J Roentgenol',
'Am J Ther',
'Am J Transl Res',
'Am J Transplant',
'Am J Trop Med Hyg',
'Am J Vet Res',
'Am Rev Respir Dis',
'Am Sci',
'Am Zool',
'Amino Acids',
'Amyloid',
'Amyotroph Lateral Scler',
'Amyotroph Lateral Scler Other Motor Neuron Disord',
'Anaesthesia',
'Anal Biochem',
'Anal Chem',
'Analyst',
'Anat Anz',
'Anat Cell Biol',
'Anat Embryol (Berl)',
'Anat Histol Embryol',
'Anat Rec (Hoboken)',
'Anat Rec A Discov Mol Cell Evol Biol',
'Anat Sci Int',
'Andrologia',
'Andrology',
'Anemia',
'Anesth Analg',
'Anesthesiology',
'Angew Chem Int Ed Engl',
'Angiogenesis',
'Angle Orthod',
'Anim Behav',
'Anim Biotech',
'Anim Biotechnol',
'Anim Blood Groups Biochem Genet',
'Anim Learn Behav',
'Ann Anat',
'Ann Biol Anim Biochim Biophys',
'Ann Clin Lab Sci',
'Ann Clin Transl Neurol',
'Ann Endocrinol (Paris)',
'Ann Eugen',
'Ann Genet',
'Ann Genet Sel Anim',
'Ann Hematol',
'Ann Inst Pasteur (Paris)',
'Ann Med',
'Ann N Y Acad Sci',
'Ann Neurol',
'Ann Nutr Metab',
'Ann Oncol',
'Ann Ophthalmol',
'Ann Otol Rhinol Laryngol',
'Ann Otol Rhinol Laryngol Suppl',
'Ann Plast Surg',
'Ann Rev Cell Dev Biol',
'Ann Rheum Dis',
'Ann Soc R Zool Belg',
'Ann Surg',
'Ann Surg Oncol',
'Ann Thorac Surg',
'Ann Transplant',
'Ann Trop Med Parasitol',
'Annee Gerontologique',
'Annu Rev Biochem',
'Annu Rev Cell Biol',
'Annu Rev Cell Dev Biol',
'Annu Rev Ecol Syst',
'Annu Rev Genet',
'Annu Rev Immunol',
'Annu Rev Med',
'Annu Rev Microbiol',
'Annu Rev Neurosci',
'Annu Rev Nutr',
'Annu Rev Pathol',
'Annu Rev Pharmacol Toxicol',
'Annu Rev Physiol',
'Antibiot Chemother',
'Anticancer Drugs',
'Anticancer Res',
'Antimicrob Agents Chemother',
'Antioxid Redox Signal',
'Antisense Nucleic Acid Drug Dev',
'Antiviral Res',
'Antonie Van Leeuwenhoek',
'APMIS',
'APMIS Suppl',
'Apoptosis',
'Appetite',
'Appl Environ Microbiol',
'Appl Opt',
'Appl Theor Electrophor',
'Arch Androl',
'Arch Biochem Biophys',
'Arch Biol (Liege)',
'Arch Dermatol',
'Arch Dermatol Res',
'Arch Dis Child',
'Arch Environ Contam Toxicol',
'Arch Environ Health',
'Arch Gen Psychiatry',
'Arch Gerontol Geriatr',
'Arch Gerontol Geriatr Suppl',
'Arch Gesamte Virusforsch',
'Arch Geschwulstforsch',
'Arch Histol Cytol',
'Arch Immunol Ther Exp (Warsz)',
'Arch Invest Med (Mex)',
'Arch Julius Klaus Stift Vererbungsforsch Sozialanthropol Rassenhyg',
'Arch Med Res',
'Arch Med Sci',
'Arch Neurol',
'Arch Ohren Nasen Kehlkopfheilkd',
'Arch Ophthalmol',
'Arch Oral Biol',
'Arch Otolaryngol',
'Arch Otolaryngol Head Neck Surg',
'Arch Otorhinolaryngol',
'Arch Pathol',
'Arch Pathol Lab Med',
'Arch Pharm (Weinheim)',
'Arch Pharm Res',
'Arch Psychology',
'Arch Surg',
'Arch Toxicol',
'Arch Toxicol Suppl',
'Arch Virol',
'Arerugi',
'Arkh Anat Gistol Embriol',
'Arq Neuropsiquiatr',
'Arterioscler Thromb',
'Arterioscler Thromb Vasc Biol',
'Arteriosclerosis',
'Arthritis Res Ther',
'Arthritis Rheum',
'Arthritis Rheumatol',
'Artif Organs',
'Arzneimittelforschung',
'ASAIO J',
'ASAIO Trans',
'Asia Pac J Clin Nutr',
'Asian J Androl',
'Asian Pac J Cancer Prev',
'ASN Neuro',
'Assay Drug Dev Technol',
'Assoc Res Otolaryngol',
'Atherosclerosis',
'Attempts to Understand Metastasis Formation III 213',
'Audiol Neurootol',
'Audiology',
'Aust J Biol Sci',
'Aust J Exp Biol Med Sci',
'Aust N Z J Med',
'Aust Vet J',
'Autism Res',
'Autoimmunity',
'Auton Neurosci',
'Autophagy',
'Aviat Space Environ Med',
'Bacteriol Rev',
'Baillieres Clin Haematol',
'Basic Clin Pharmacol Toxicol',
'Basic Life Sci',
'Basic Res Cardiol',
'Behav Biol',
'Behav Brain Funct',
'Behav Brain Res',
'Behav Brain Sci',
'Behav Healthc',
'Behav Neural Biol',
'Behav Neurosci',
'Behav Pharmacol',
'Behav Processes',
'Behav Res Methods Instrum Comput',
'Behaviour',
'Behring Inst Mitt',
'Biocell',
'Biochem Arch',
'Biochem Cell Biol',
'Biochem Genet',
'Biochem Int',
'Biochem Med Metab Biol',
'Biochem Mol Biol Int',
'Biochem Mol Med',
'Biochem Pharmacol',
'Biochem Soc Symp',
'Biochem Soc Trans',
'Biochemistry',
'Biochemistry (Mosc)',
'Biochimie',
'Bioconjug Chem',
'Bioelectromagnetics',
'Bioeng Bugs',
'Bioengineered',
'Bioessays',
'Biofactors',
'Biogenic Amines',
'Biogerontology',
'Bioinformatics',
'Bioinorg Chem',
'Biokhimiia',
'Biol Blood Marrow Transplant',
'Biol Cell',
'Biol Chem',
'Biol Chem Hoppe Seyler',
'Biol J Linnean Soc',
'Biol Neonate',
'Biol Pharm Bull',
'Biol Psychiatry',
'Biol Res',
'Biol Rev Camb Philos Soc',
'Biol Rhythm Res',
'Biol Sci Space',
'Biol Signals',
'Biol Trace Elem Res',
'Biol Zentralbl',
'Biomarkers',
'Biomaterials',
'Biomed Biochim Acta',
'Biomed Environ Sci',
'Biomed Pept Proteins Nucleic Acids',
'Biomed Pharmacother',
'Biomed Res',
'Biomed Res Int',
'Biomedicine',
'Biomedicines',
'Biometals',
'Biometrics',
'Biomol Eng',
'Biomolecules',
'Bioorg Khim',
'Bioorg Med Chem',
'Bioorg Med Chem Lett',
'Biopharm Drug Dispos',
'Biophys Chem',
'Biophys J',
'Bioresour Technol',
'Biorheology',
'Biosci Biotechnol Biochem',
'Biosci Rep',
'Biosens Bioelectron',
'Biotech Histochem',
'Biotechnol Annu Rev',
'Biotechnol Lett',
'Biotechnology',
'Biotherapy',
'Birth Defects',
'Birth Defects Orig Artic Ser',
'Birth Defects Res A Clin Mol Teratol',
'Birth Defects Res B Dev Reprod Toxicol',
'Birth Defects Res Part A Clin Mol Teratol',
'Biull Eksp Biol Med',
'BJR Suppl',
'BJU Int',
'Blood Cancer J',
'Blood Cells',
'Blood Cells Mol Dis',
'Blood Coagul Fibrinolysis',
'Blood Press',
'Blut',
'BMB Rep',
'BMC Biochem',
'BMC Bioinformatics',
'BMC Biol',
'BMC Biotechnol',
'BMC Blood Disord',
'BMC Cancer',
'BMC Cell Biol',
'BMC Complement Altern Med',
'BMC Dev Biol',
'BMC Gastroenterol',
'BMC Immunol',
'BMC Med',
'BMC Med Genet',
'BMC Mol Biol',
'BMC Musculoskelet Disord',
'BMC Nephrol',
'BMC Neurosci',
'BMC Ophthalmol',
'BMC Pharmacol Toxicol',
'BMC Physiol',
'BMC Struct Biol',
'BMC Syst Biol',
'BMJ',
'BMJ Open',
'Bone',
'Bone Marrow Transplant',
'Bone Miner',
'Bone Res',
'Bonekey Rep',
'Br Heart J',
'Br J Biomed Sci',
'Br J Cancer',
'Br J Dermatol',
'Br J Exp Pathol',
'Br J Haematol',
'Br J Nutr',
'Br J Ophthalmol',
'Br J Pharmacol',
'Br J Radiol',
'Br J Surg',
'Br Med Bull',
'Br Med J',
'Br Vet J',
'Brain',
'Brain Behav',
'Brain Behav Immun',
'Brain Cell Biol',
'Brain Dev',
'Brain Lang',
'Brain Nerve (Tokyo)',
'Brain Res',
'Brain Res Brain Res Protoc',
'Brain Res Brain Res Rev',
'Brain Res Bull',
'Brain Res Cogn Brain Res',
'Brain Res Dev Brain Res',
'Brain Res Gene Expr Patterns',
'Brain Res Mol Brain Res',
'Brain Struct Funct',
'Braz J Med Biol Res',
'Breast Cancer',
'Breast Cancer Res Treat',
'Breast Dis',
'Brief Funct Genomic Proteomic',
'Bull Cancer',
'Bull Cancer (Paris)',
'Bull Environ Contam Toxicol',
'Bull Eur Physiopathol Respir',
'Bull Exp Anim',
'Bull Exp Biol Med',
'Bull N Y Acad Med',
'Bull Natl Inst Agri Sci',
'Bull World Health Organ',
'Burns',
'C R Acad Sci Hebd Seances Acad Sci D',
'C R Acad Sci III',
'C R Biol',
'C R Hebd Seances Acad Sci',
'C R Seances Acad Sci D',
'C R Seances Acad Sci III',
'C R Seances Soc Biol Fil',
'CA Cancer J Clin',
'Calcif Tissue Int',
'Calif Med',
'Can J Anim Sci',
'Can J Biochem',
'Can J Cardiol',
'Can J Genet Cytol',
'Can J Microbiol',
'Can J Neurol Sci',
'Can J Physiol Pharmacol',
'Can J Psychol',
'Can J Res',
'Cancer',
'Cancer Biochem Biophys',
'Cancer Biol Ther',
'Cancer Biomark',
'Cancer Biother',
'Cancer Biother Radiopharm',
'Cancer Cell',
'Cancer Cell Int',
'Cancer Cells',
'Cancer Chemother Pharmacol',
'Cancer Commun',
'Cancer Detect Prev',
'Cancer Discov',
'Cancer Epidemiol Biomarkers Prev',
'Cancer Gene Ther',
'Cancer Genet',
'Cancer Genet Cytogenet',
'Cancer Immun',
'Cancer Immunol Immunother',
'Cancer Invest',
'Cancer J',
'Cancer J Sci Am',
'Cancer Lett',
'Cancer Metab',
'Cancer Metastasis Rev',
'Cancer Prev Res (Phila)',
'Cancer Sci',
'Cancer Surv',
'Cancer Treat Res',
'Cancers (Basel)',
'Carcinog Compr Surv',
'Carcinogenesis',
'Cardiovasc Diabetol',
'Cardiovasc Pathol',
'Cardiovasc Res',
'Cardiovasc Res Cent Bull',
'Caries Res',
'Cell Adh Migr',
'Cell Adhes Commun',
'Cell Biochem Biophys',
'Cell Biochem Funct',
'Cell Biol Int',
'Cell Biol Int Rep',
'Cell Biol Toxicol',
'Cell Biosci',
'Cell Calcium',
'Cell Commun Adhes',
'Cell Commun Signal',
'Cell Cycle',
'Cell Death Differ',
'Cell Death Dis',
'Cell Differ',
'Cell Differ Dev',
'Cell Discov',
'Cell Div',
'Cell Growth Differ',
'Cell Host Microbe',
'Cell Immunol',
'Cell Metab',
'Cell Microbiol',
'Cell Mol Biol',
'Cell Mol Biol (Noisy-Le-Grand)',
'Cell Mol Biol Lett',
'Cell Mol Biol Res',
'Cell Mol Gastroenterol Hepatol',
'Cell Mol Immunol',
'Cell Mol Life Sci',
'Cell Mol Neurobiol',
'Cell Motil Cytoskeleton',
'Cell Physiol Biochem',
'Cell Prolif',
'Cell Regul',
'Cell Res',
'Cell Signal',
'Cell Stress Chaperones',
'Cell Struct Funct',
'Cell Syst',
'Cell Tissue Kinet',
'Cell Tissue Res',
'Cell Transplant',
'Cells Tissues Organs',
'Cereb Cortex',
'Cerebellum',
'Cerebrovasc Dis',
'Challenges Mod Med',
'Channels (Austin)',
'Chem Biodivers',
'Chem Biol',
'Chem Biol Interact',
'Chem Immunol',
'Chem Pharm Bull (Tokyo)',
'Chem Pharm Bull Tokyo',
'Chem Phys Lipids',
'Chem Res Toxicol',
'Chem Senses',
'Chemica Scripta',
'Chemosphere',
'Chest',
'Chest Surg Clin N Am',
'Childs Nerv Syst',
'Chin J Dig Dis',
'Chin J Physiol',
'Chin Med J (Engl)',
'Chromosoma',
'Chromosome Res',
'Chromosomes Today',
'Chronobiol Int',
'Chung Hua Kou Chiang Ko Tsa Chih',
'Ciba Found Symp',
'Cilia',
'Circ Arrhythm Electrophysiol',
'Circ Cardiovasc Genet',
'Circ Heart Fail',
'Circ J',
'Circ Res',
'Circ Shock',
'Cleft Palate Craniofac J',
'Cleft Palate J',
'Clin Biochem',
'Clin Cancer Res',
'Clin Chim Acta',
'Clin Dev Immunol',
'Clin Diagn Lab Immunol',
'Clin Dysmorphol',
'Clin Endocrinol (Oxf)',
'Clin Exp Allergy',
'Clin Exp Dermatol',
'Clin Exp Gastroenterol',
'Clin Exp Hypertens',
'Clin Exp Immunol',
'Clin Exp Metastasis',
'Clin Exp Pharmacol Physiol',
'Clin Exp Rheumatol',
'Clin Genet',
'Clin Immunol',
'Clin Immunol Immunopathol',
'Clin Immunol Newsletter',
'Clin Infect Dis',
'Clin Invest Med',
'Clin Med Res',
'Clin Neuropharmacol',
'Clin Orthod Res',
'Clin Orthop',
'Clin Pediatr Endocrinol',
'Clin Phys Physiol Meas',
'Clin Plast Surg',
'Clin Rev Allergy Immunol',
'Clin Sci',
'Clin Sci (Colch)',
'Clin Sci (Lond)',
'Clin Transl Oncol',
'Clin Transplant',
'Clin Vaccine Immunol',
'Cloning Stem Cells',
'CNS Neurosci Ther',
'Cold Spring Harb Perspect Biol',
'Cold Spring Harb Protoc',
'Cold Spring Harb Symp Quant Biol',
'Coll Antropol',
'Coll Int Centre Natl Recherche Sci',
'Colloids Surf B Biointerfaces',
'Commun Behav Biol',
'Comp Biochem Physiol',
'Comp Biochem Physiol [B]',
'Comp Biochem Physiol [C]',
'Comp Biochem Physiol A',
'Comp Biochem Physiol A Mol Integr Physiol',
'Comp Biochem Physiol A Physiol',
'Comp Biochem Physiol B Biochem Mol Biol',
'Comp Biochem Physiol Biochem Mol Biol',
'Comp Biochem Physiol C',
'Comp Biochem Physiol C Pharmacol Toxicol Endocrinol',
'Comp Biochem Physiol Comp Physiol',
'Comp Biochem Physiol Part D Genomics Proteomics',
'Comp Funct Genomics',
'Comp Haematol Int',
'Comp Immunol Microbiol Infect Dis',
'Comp Med',
'Comp Pathol Bull',
'Comput Biol Chem',
'Comput Biol Med',
'Comput Struct Biotechnol J',
'Concepts Immunopathol',
'Congenit Anom (Kyoto)',
'Connect Tissue Res',
'Contact Dermatitis',
'Contemp Top Lab Anim Sci',
'Contemp Top Mol Immunol',
'Contemp Topics',
'Contrib Nephrol',
'Cornea',
'Crit Care Med',
'Crit Rev Biochem Mol Biol',
'Crit Rev Eukaryot Gene Expr',
'Crit Rev Food Sci Nutr',
'Crit Rev Immunol',
'Crit Rev Neurobiol',
'Crit Rev Oncog',
'Crit Rev Oral Biol Med',
'Crit Rev Toxicol',
'Cryobiology',
'Curr Alzheimer Res',
'Curr Biol',
'Curr Cancer Drug Targets',
'Curr Dir Autoimmun',
'Curr Drug Discov Technol',
'Curr Drug Targets Immune Endocr Metabol Disord',
'Curr Eye Res',
'Curr Gene Ther',
'Curr Genomics',
'Curr Hypertens Rep',
'Curr Microbiol',
'Curr Mol Med',
'Curr Oncol Rep',
'Curr Opin Biotechnol',
'Curr Opin Cell Biol',
'Curr Opin Genet Dev',
'Curr Opin Hematol',
'Curr Opin Immunol',
'Curr Opin Lipidol',
'Curr Opin Nephrol Hypertens',
'Curr Opin Neurobiol',
'Curr Opin Neurol',
'Curr Opin Oncol',
'Curr Opin Pediatr',
'Curr Opin Pharmacol',
'Curr Opin Pulm Med',
'Curr Opin Rheumatol',
'Curr Opin Struct Biol',
'Curr Pharm Biotechnol',
'Curr Protoc Immunol',
'Curr Rheumatol Rep',
'Curr Top Dev Biol',
'Curr Top Microbiol Immunol',
'Current Zoology',
'Cutis',
'Cytobios',
'Cytogenet Genome Res',
'Cytogenetics',
'Cytokine',
'Cytokine Growth Factor Rev',
'Cytokine Knockouts',
'Cytokines Cell Mol Ther',
'Cytokines Mol Ther',
'Cytologia (Tokyo)',
'Cytometry',
'Cytoskeleton (Hoboken)',
'Cytotechnology',
'Dan Med Bull',
'Data Brief',
'Database (Oxford)',
'Dementia',
'Dermatoendocrinol',
'Dermatol Online J',
'Dermatologica',
'Dermatology',
'Dev Biol Stand',
'Dev Brain Dysfunct',
'Dev Comp Immunol',
'Dev Genes Evol',
'Dev Growth Differ',
'Dev Immunol',
'Dev Med Child Neurol',
'Dev Neurobiol',
'Dev Neurosci',
'Dev Pharmacol Ther',
'Dev Psychobiol',
'Dev Suppl',
'Development',
'Diabete Metab',
'Diabetes Metab',
'Diabetes Metab Res Rev',
'Diabetes Metab Rev',
'Diabetes Metab Syndr Obes',
'Diabetes Nutr Metab',
'Diabetes Obes Metab',
'Diabetes Res',
'Diabetes Res Clin Pract',
'Diabetologia',
'Diagn Microbiol Infect Dis',
'Dialogues Clin Neurosci',
'Differentiation',
'Dig Dis Sci',
'Dig Liver Dis',
'Dig Surg',
'Digestion',
'Dis Colon Rectum',
'Dis Esophagus',
'Dis Model Mech',
'DNA',
'DNA Cell Biol',
'DNA Repair (Amst)',
'DNA Seq',
'Doc Ophthalmol',
'Dokl Akad Nauk',
'Dokl Akad Nauk SSSR',
'Dokl Biol Sci',
'Domest Anim Endocrinol',
'Dose Response',
'Drug Alcohol Depend',
'Drug Chem Toxicol',
'Drug Deliv Transl Res',
'Drug Metab Dispos',
'Drug Metab Rev',
'Drug Metabol Drug Interact',
'Drug News Perspect',
'Drugs Exp Clin Res',
'Ear Hear',
'EBioMedicine',
'Ecotoxicol Environ Saf',
'Eksp Onkol',
'Electro Magnetobiol',
'Electroencephalogr Clin Neurophysiol',
'Electromyogr Clin Neurophysiol',
'Electrophoresis',
'Elife',
'EMBO Rep',
'Emerg Infect Dis',
'Endocr J',
'Endocr Pathol',
'Endocr Regul',
'Endocr Relat Cancer',
'Endocr Res',
'Endocr Rev',
'Endocrine',
'Endocrine Res',
'Endocrinol Exp',
'Endocrinol Jpn',
'Endocrinol Metab Clin North Am',
'Endothelium',
'eNeuro',
'Environ Health Perspect',
'Environ Mol Mutagen',
'Environ Mutagen',
'Environ Res',
'Environ Sci',
'Environ Sci Technol',
'Environ Toxicol Pharmacol',
'Enzyme',
'Enzyme Protein',
'Epidemiol Infect',
'Epigenetics',
'Epigenetics Chromatin',
'Epigenomics',
'Epilepsia',
'Epilepsy Res',
'Epilepsy Res Suppl',
'Epithelia',
'Epithelial Cell Biol',
'Erbarzt',
'Ethology',
'Eur Biophys J',
'Eur Heart J',
'Eur J Biochem',
'Eur J Cancer',
'Eur J Cancer B Oral Oncol',
'Eur J Cancer Clin Oncol',
'Eur J Cancer Prev',
'Eur J Cardiothorac Surg',
'Eur J Cell Biol',
'Eur J Clin Chem Clin Biochem',
'Eur J Clin Invest',
'Eur J Clin Microbiol Infect Dis',
'Eur J Clin Nutr',
'Eur J Dermatol',
'Eur J Endocrinol',
'Eur J Epidemiol',
'Eur J Gastroenterol Hepatol',
'Eur J Haematol',
'Eur J Histochem',
'Eur J Hum Genet',
'Eur J Immunogenet',
'Eur J Immunol',
'Eur J Med Chem',
'Eur J Med Res',
'Eur J Morphol',
'Eur J Neurosci',
'Eur J Nucl Med Mol Imaging',
'Eur J Nutr',
'Eur J Obstet Gynecol Reprod Biol',
'Eur J Ophthalmol',
'Eur J Oral Sci',
'Eur J Orthod',
'Eur J Pediatr Surg',
'Eur J Pharmacol',
'Eur Neuropsychopharmacol',
'Eur Respir J',
'Eur Respir J Suppl',
'Eur Rev Med Pharmacol Sci',
'Eur Surg Res',
'Eur Thyroid J',
'Eur Urol',
'Eurocancer 98',
'Evid Based Complement Alternat Med',
'Evol Dev',
'Evolution Int J Org Evolution',
'Exp Aging Res',
'Exp Anim',
'Exp Biol',
'Exp Biol Med (Maywood)',
'Exp Cell Biol',
'Exp Cell Res',
'Exp Clin Endocrinol',
'Exp Clin Endocrinol Diabetes',
'Exp Clin Immunogenet',
'Exp Dermatol',
'Exp Diabetes Res',
'Exp Gerontol',
'Exp Lung Res',
'Exp Med Surg',
'Exp Mol Med',
'Exp Nephrol',
'Exp Neurobiol',
'Exp Neurol',
'Exp Oncol',
'Exp Parasitol',
'Exp Pathol',
'Exp Physiol',
'Exp Ther Med',
'Exp Toxicol Pathol',
'Expert Opin Drug Metab Toxicol',
'Expert Opin Ther Patents',
'Expert Opin Ther Targets',
'Expert Rev Anticancer Ther',
'Expert Rev Neurother',
'Expert Rev Vaccines',
'EXS',
'Eye (Lond)',
'F1000Res',
'Fam Cancer',
'Farmaco',
'Farmaco Sci',
'FEBS J',
'FEBS Open Bio',
'FEMS Immunol Med Microbiol',
'FEMS Microbiol Immunol',
'FEMS Microbiol Lett',
'Fibrinolysis',
'Fibrinolysis Proteolysis',
'Fluids Barriers CNS',
'Folia Biol (Krakow)',
'Folia Biol (Praha)',
'Folia Histochem Cytobiol',
'Folia Histochem Cytochem (Krakow)',
'Folia Microbiol (Praha)',
'Folia Morphol (Warsz)',
'Food Addit Contam',
'Food Chem Toxicol',
'Forensic Sci Int',
'Frankf Z Pathol',
'Free Radic Biol Med',
'Free Radic Res',
'Free Radic Res Commun',
'Front Behav Neurosci',
'Front Biosci',
'Front Biosci (Elite Ed)',
'Front Cardiovasc Med',
'Front Cell Dev Biol',
'Front Cell Neurosci',
'Front Endocrinol (Lausanne)',
'Front Genet',
'Front Horm Res',
'Front Immunol',
'Front Microbiol',
'Front Neural Circuits',
'Front Neuroanat',
'Front Neuroendocrinol',
'Front Neuroenergetics',
'Front Neurosci',
'Front Oncol',
'Front Pharmacol',
'Front Physiol',
'Front Syst Neurosci',
'Funct Integr Genomics',
'Functional Endocrinology of Aging 29',
'Fundam Appl Toxicol',
'Fundam Clin Pharmacol',
'Future Oncol',
'G3 (Bethesda)',
'Gann',
'Gap Junctions',
'Gastroenterol Clin Biol',
'Gastrointest Endosc',
'Gen Comp Endocrinol',
'Gen Pharmacol',
'Gen Physiol Biophys',
'Gene',
'Gene Expr',
'Gene Expr Patterns',
'Gene Ther',
'Genes (Basel)',
'Genes Brain Behav',
'Genes Cancer',
'Genes Chromosomes Cancer',
'Genes Dev',
'Genes Funct',
'Genes Genet Syst',
'Genes Nutr',
'Genet Anal',
'Genet Anal Tech Appl',
'Genet Epidemiol',
'Genet Mol Biol',
'Genet Mol Res',
'Genet Res (Camb)',
'Genet Sel Evol',
'Genet Today',
'Genetics in Wild Mice',
'Genetika',
'Genom Data',
'Genome Biol',
'Genome Lett',
'Genome Med',
'Genome Priority Reports',
'Gerontologia',
'Gerontology',
'Glia',
'Glycobiology',
'Glycoconj J',
'Graefes Arch Clin Exp Ophthalmol',
'Growth',
'Growth Dev Aging',
'Growth Factors',
'Growth Horm IGF Res',
'Growth Regul',
'Gut',
'Gynecol Obstet Invest',
'Gynecol Oncol',
'Haematol Blood Transfus',
'Haematologica',
'Haemostasis',
'Hamatol Bluttransfus',
'Harvey Lect',
'Head Neck',
'Hear Res',
'Heart Rhythm',
'Helicobacter',
'Hematol Cell Ther',
'Hematol J',
'Hematol Oncol',
'Hematol Oncol Clin North Am',
'Hepatobiliary Pancreat Dis Int',
'Hepatogastroenterology',
'Hepatol Res',
'Heredity (Edinb)',
'Hippocampus',
'Histochem Cell Biol',
'Histochem J',
'Histochemistry',
'Histol Histopathol',
'Histopathology',
'Hokkaido Igaku Zasshi',
'Horm Behav',
'Horm Cancer',
'Horm Metab Res',
'Horm Res',
'Hum Antibodies',
'Hum Antibodies Hybridomas',
'Hum Biol',
'Hum Cell',
'Hum Exp Toxicol',
'Hum Gene Ther',
'Hum Gene Ther Methods',
'Hum Genet',
'Hum Genomics',
'Hum Hered',
'Hum Immunol',
'Hum Mutat',
'Hum Pathol',
'Hum Reprod Update',
'Humangenetik',
'Hybrid Hybridomics',
'Hybridoma',
'Hybridoma (Larchmt)',
'Hypertens Res',
'Hypertension',
'I Chuan Hsueh Pao',
'IARC Sci Publ',
'ILAR J',
'ILAR News',
'Immun Ageing',
'Immun Inflamm Dis',
'Immunity',
'Immunobiology',
'Immunochemistry',
'Immunodefic Rev',
'Immunodeficiency',
'Immunol Cell Biol',
'Immunol Invest',
'Immunol Lett',
'Immunol Res',
'Immunol Rev',
'Immunol Today',
'Immunology',
'Immunome Res',
'Immunopharmacol Immunotoxicol',
'Immunopharmacology',
'In Vitro',
'In Vitro Cell Dev Biol',
'In Vitro Cell Dev Biol Anim',
'In Vivo',
'Ind Health',
'Indian J Biochem Biophys',
'Indian J Exp Biol',
'Indian J Hum Genet',
'Indian J Med Res',
'Indian J Pathol Microbiol',
'Indian J Physiol Pharmacol',
'Infect Genet Evol',
'Infect Immun',
'Inflamm Bowel Dis',
'Inflamm Res',
'Inflammation',
'Inflammopharmacology',
'Inhal Toxicol',
'Innate Immun',
'Int Arch Allergy Appl Immunol',
'Int Arch Allergy Immunol',
'Int Immunol',
'Int Immunopharmacol',
'Int J Androl',
'Int J Audiol',
'Int J Biochem',
'Int J Biochem Cell Biol',
'Int J Biol Sci',
'Int J Cancer',
'Int J Cancer Suppl',
'Int J Cardiol',
'Int J Cell Biol',
'Int J Cell Cloning',
'Int J Clin Exp Pathol',
'Int J Clin Lab Res',
'Int J Clin Pharmacol Ther',
'Int J Colorectal Dis',
'Int J Dermatol',
'Int J Dev Neurosci',
'Int J Endocrinol',
'Int J Exp Diabetes Res',
'Int J Gastrointest Cancer',
'Int J Genome Res',
'Int J Genomics',
'Int J Gynecol Cancer',
'Int J Hematol',
'Int J Hyperthermia',
'Int J Immunopathol Pharmacol',
'Int J Immunopharmacol',
'Int J Immunother',
'Int J Legal Med',
'Int J Lepr Other Mycobact Dis',
'Int J Med Microbiol',
'Int J Med Sci',
'Int J Mol Med',
'Int J Mol Sci',
'Int J Neurol',
'Int J Neuropsychopharmacol',
'Int J Neurosci',
'Int J Obes',
'Int J Obes (Lond)',
'Int J Obes Relat Metab Disord',
'Int J Oncol',
'Int J Oral Sci',
'Int J Pancreatol',
'Int J Parasitol',
'Int J Pediatr Otorhinolaryngol',
'Int J Pept Protein Res',
'Int J Physiol Pathophysiol Pharmacol',
'Int J Rad Appl Instrum [B]',
'Int J Radiat Biol',
'Int J Radiat Biol Relat Stud Phys Chem Med',
'Int J Radiat Oncol Biol Phys',
'Int J Tissue React',
'Int J Toxicol',
'Int J Urol',
'Int J Vitam Nutr Res',
'Int Rev Cytol',
'Int Rev Immunol',
'Int Urol Nephrol',
'Integr Cancer Ther',
'Intervirology',
'Invasion Metastasis',
'Invest New Drugs',
'Invest Ophthalmol',
'Invest Radiol',
'Iowa State J Res',
'Islets',
'Isr J Med Sci',
'Ital J Anat Embryol',
'Ital J Neurol Sci',
'IUBMB Life',
'J AAPOS',
'J Abnorm Soc Psychol',
'J Acoust Soc Am',
'J Acquir Immune Defic Syndr',
'J Acquir Immune Defic Syndr Hum Retrovirol',
'J Addict Dis',
'J Agr Food Chem',
'J Agric Food Chem',
'J Allergy Clin Immunol',
'J Altern Complement Med',
'J Alzheimers Dis',
'J Am Acad Child Adolesc Psychiatry',
'J Am Acad Dermatol',
'J Am Coll Cardiol',
'J Am Coll Nutr',
'J Am Geriatr Soc',
'J Am Med Assoc',
'J Am Soc Nephrol',
'J Amino Acids',
'J Androl',
'J Anesth',
'J Anim Ecol',
'J Antimicrob Chemother',
'J Appl Bacteriol',
'J Appl Genet',
'J Appl Physiol',
'J Appl Physiol (1985)',
'J Appl Toxicol',
'J Asian Nat Prod Res',
'J Assoc Res Otolaryngol',
'J Atheroscler Thromb',
'J Aud Res',
'J Autoimmun',
'J Auton Nerv Syst',
'J Bacteriol',
'J Basic Clin Physiol Pharmacol',
'J Biochem',
'J Biochem Mol Biol',
'J Biochem Mol Toxicol',
'J Biochem Toxicol',
'J Bioenerg Biomembr',
'J Biol',
'J Biol Regul Homeost Agents',
'J Biol Rhythms',
'J Biomed Biotechnol',
'J Biomed Opt',
'J Biomed Res',
'J Biomed Sci',
'J Biomol NMR',
'J Biomol Tech',
'J Biophys Biochem Cytol',
'J Biosci',
'J Biosci Bioeng',
'J Biotechnol',
'J Bone Joint Surg Am',
'J Bone Joint Surg Br',
'J Bone Miner Metab',
'J Burn Care Rehabil',
'J Cancer',
'J Cancer Biol Res',
'J Cancer Res',
'J Cancer Res Clin Oncol',
'J Carcinog',
'J Card Fail',
'J Cardiovasc Electrophysiol',
'J Cardiovasc Pharmacol',
'J Cardiovasc Pharmacol Ther',
'J Cardiovasc Transl Res',
'J Cataract Refract Surg',
'J Cell Biochem',
'J Cell Biochem Suppl',
'J Cell Biol',
'J Cell Commun Signal',
'J Cell Comp Physiol',
'J Cell Mol Med',
'J Cell Physiol',
'J Cell Sci',
'J Cell Sci Suppl',
'J Cereb Blood Flow Metab',
'J Chem Neuroanat',
'J Chemother',
'J Child Neurol',
'J Chromatogr B Biomed Appl',
'J Circadian Rhythms',
'J Clin Endocrinol',
'J Clin Endocrinol Metab',
'J Clin Immunol',
'J Clin Invest',
'J Clin Lab Immunol',
'J Clin Microbiol',
'J Clin Neurosci',
'J Clin Oncol',
'J Clin Pathol',
'J Clin Psychiatry',
'J Coll Physicians Surg Pak',
'J Comp Neurol',
'J Comp Pathol',
'J Comp Physiol [A]',
'J Comp Physiol Psychol',
'J Comp Psychol',
'J Control Release',
'J Craniofac Genet Dev Biol Suppl',
'J Craniofac Surg',
'J Cutan Med Surg',
'J Cutan Pathol',
'J Cyst Fibros',
'J Dairy Sci',
'J Dent Res',
'J Dermatol',
'J Dermatol Sci',
'J Dev Physiol',
'J Diabetes Investig',
'J Drug Target',
'J Drugs Dermatol',
'J Egypt Soc Parasitol',
'J Electron Microsc (Tokyo)',
'J Embryol Exp Morphol',
'J Endocrin',
'J Endocrinol Invest',
'J Endod',
'J Endotoxin Res',
'J Endourol',
'J Environ Pathol Toxicol',
'J Environ Pathol Toxicol Oncol',
'J Environ Sci Health B',
'J Environ Sci Health C Environ Carcinog Ecotoxicol Rev',
'J Environ Sci Health Part A Tox Hazard Subst Environ Eng',
'J Epidemiol',
'J Ethnopharmacol',
'J Eukaryot Microbiol',
'J Evol Biol',
'J Exp Anim Sci',
'J Exp Biol',
'J Exp Bot',
'J Exp Clin Cancer Res',
'J Exp Pathol',
'J Exp Pathol (Oxford)',
'J Exp Ther Oncol',
'J Exp Zool B Mol Dev Evol',
'J Exp Zoolog A Comp Exp Biol',
'J Exp Zoolog B Mol Dev Evol',
'J Exp Zoolog Part A Comp Exp Biol',
'J Gastroenterol',
'J Gastroenterol Hepatol',
'J Gastrointest Surg',
'J Gen Microbiol',
'J Gen Physiol',
'J Gen Psychol',
'J Gen Virol',
'J Gene Med',
'J Genet Genomics',
'J Genet Mol Biol',
'J Genet Psychol',
'J Gerontol',
'J Gerontol A Biol Sci Med Sci',
'J Glaucoma',
'J Gravit Physiol',
'J Hand Surg [Am]',
'J Hard Tissue Biol',
'J Heart Lung Transplant',
'J Heart Transplant',
'J Helminthol',
'J Hematol Oncol',
'J Hematother Stem Cell Res',
'J Hepatobiliary Pancreat Surg',
'J Hepatol',
'J Hirnforsch',
'J Histochem Cytochem',
'J Huazhong Univ Sci Technolog Med Sci',
'J Hum Genet',
'J Hyg (Lond)',
'J Hypertens',
'J Immunogenet',
'J Immunol Methods',
'J Immunol Res',
'J Immunother',
'J Immunother Emphasis Tumor Immunol',
'J Immunotoxicol',
'J Infect',
'J Infect Dis',
'J Inflamm',
'J Inherit Metab Dis',
'J Innate Immun',
'J Int Med Res',
'J Interferon Cytokine Res',
'J Interferon Res',
'J Intern Med',
'J Interv Card Electrophysiol',
'J Invest Dermatol Symp Proc',
'J Invest Surg',
'J Investig Dermatol',
'J Investig Dermatol Symp Proc',
'J Investig Med',
'J Korean Med Sci',
'J La State Med Soc',
'J Lab Clin Med',
'J Leukoc Biol',
'J Leukoc Biol Suppl',
'J Lipid Mediat',
'J Lipid Mediat Cell Signal',
'J Lipid Res',
'J Magn Reson Imaging',
'J Mammal',
'J Mammary Gland Biol Neoplasia',
'J Matern Fetal Neonatal Med',
'J Med Chem',
'J Med Entomol',
'J Med Food',
'J Med Genet',
'J Med Invest',
'J Med Microbiol',
'J Med Res',
'J Med Sci',
'J Med Vet Mycol',
'J Med Virol',
'J Membr Biol',
'J Microbiol Biotechnol',
'J Microencapsul',
'J Microsc',
'J Mol Appl Genet',
'J Mol Biol',
'J Mol Cell Biol',
'J Mol Cell Cardiol',
'J Mol Cell Immunol',
'J Mol Endocrinol',
'J Mol Evol',
'J Mol Histol',
'J Mol Med',
'J Mol Med (Berl)',
'J Mol Neurosci',
'J Mol Recognit',
'J Mol Signal',
'J Muscle Res Cell Motil',
'J Musculoskelet Neuronal Interact',
'J Nanosci Nanotechnol',
'J Nat Prod',
'J Natl Cancer Inst Monogr',
'J Negat Results Biomed',
'J Nephrol',
'J Neural Transm',
'J Neural Transm Gen Sect',
'J Neural Transm Suppl',
'J Neural Transplant',
'J Neurobiol',
'J Neurocytol',
'J Neurodev Disord',
'J Neuroendocrinol',
'J Neurogenet',
'J Neuroimmunol',
'J Neuroinflammation',
'J Neurol',
'J Neurol Neurosurg Psychiatry',
'J Neurol Sci',
'J Neurooncol',
'J Neurophysiol',
'J Neurosci (Online)',
'J Neurosci Methods',
'J Neurosci Res',
'J Neurosurg',
'J Neurotrauma',
'J Neurovirol',
'J NIH Res',
'J Nippon Med Sch',
'J Nucl Med',
'J Nutr',
'J Nutr Biochem',
'J Nutr Health Aging',
'J Nutr Sci Vitaminol (Tokyo)',
'J Nutrigenet Nutrigenomics',
'J Occup Health',
'J Ocul Pharmacol Ther',
'J Ophthalmol',
'J Opt Soc Am A',
'J Oral Pathol Med',
'J Oral Sci',
'J Oral Surg',
'J Orthop Res',
'J Osteoporos',
'J Parasitol',
'J Pathol Bacteriol',
'J Pediatr Endocrinol Metab',
'J Pediatr Gastroenterol Nutr',
'J Pediatr Hematol Oncol',
'J Pediatr Surg',
'J Periodontal Res',
'J Periodontol',
'J Peripher Nerv Syst',
'J Pharm Pharmacol',
'J Pharm Sci',
'J Pharmacol Exp Ther',
'J Pharmacol Sci',
'J Pharmacol Toxicol Methods',
'J Photochem Photobiol B',
'J Physiol Biochem',
'J Physiol Paris',
'J Physiol Pharmacol',
'J Physiol Sci',
'J Pineal Res',
'J Protein Chem',
'J Proteome Res',
'J Proteomics',
'J Protozool',
'J Psychiatr Res',
'J Psychiatry Neurosci',
'J Psychol',
'J Psychopharmacol',
'J Radiat Res',
'J Radiat Res (Tokyo)',
'J Radiol Prot',
'J Recept Res',
'J Recept Signal Transduct Res',
'J Renin Angiotensin Aldosterone Syst',
'J Reprod Dev',
'J Reprod Fertil Suppl',
'J Reprod Immunol',
'J Rheumatol',
'J RNAi Gene Silencing',
'J Skin Cancer',
'J Sleep Res',
'J Soc Gynecol Investig',
'J Steroid Biochem',
'J Struct Biol',
'J Struct Funct Genomics',
'J Stud Alcohol',
'J Submicrosc Cytol',
'J Submicrosc Cytol Pathol',
'J Subst Abuse',
'J Supramol Struct',
'J Supramol Struct Cell Biochem',
'J Surg Oncol',
'J Surg Res',
'J Theor Biol',
'J Thorac Cardiovasc Surg',
'J Thromb Haemost',
'J Toxicol Environ Health',
'J Toxicol Environ Health A',
'J Toxicol Environ Health B Crit Rev',
'J Toxicol Environ Health Suppl',
'J Toxicol Pathol',
'J Toxicol Sci',
'J Trace Elem Exp Med',
'J Trace Elem Med Biol',
'J Trauma',
'J Trop Med Hyg',
'J Ultrastruct Res',
'J Urol',
'J Vasc Res',
'J Vasc Surg',
'J Vet Diagn Invest',
'J Vet Med Sci',
'J Vet Sci',
'J Viral Hepat',
'J Virol',
'J Virol Methods',
'J Vis Exp',
'J Zhejiang Univ Sci B',
'J Zool',
'JAKSTAT',
'JAMA',
'JAMA Neurol',
'Jikeikai Med J',
'Jikken Dobutsu',
'Jikken Dobutsu (Exp Anim)',
'Jinrui Idengaku Zasshi',
'JPEN J Parenter Enteral Nutr',
'Jpn Circ J',
'Jpn Heart J',
'Jpn J Cancer Res',
'Jpn J Clin Pathol',
'Jpn J Exp Med',
'Jpn J Genet',
'Jpn J Hum Genet',
'Jpn J Med',
'Jpn J Ophthalmol',
'Jpn J Oral Biol',
'Jpn J Pharmacol',
'Jpn J Physiol',
'Jpn J Psychiatry Neurol',
'Jpn J Vet Res',
'Jpn J Zootech Sci',
'JSLS',
'Kaibogaku Zasshi',
'Kansenshogaku Zasshi',
'Keio J Med',
'Kidney Blood Press Res',
'Kidney Int',
'Kidney Int Suppl',
'Kisaengchunghak Chapchi',
'Kobe J Med Sci',
'Korean J Biochem',
'Korean J Ophthalmol',
'Korean J Physiol Pharmacol',
'Kurume Med J',
'Lab Anim',
'Lab Anim (NY)',
'Lab Anim Care',
'Lab Anim Sci',
'Lab Animal',
'Lancet',
'Langenbecks Arch Surg',
'Langmuir',
'Laryngoscope',
'Lasers Med Sci',
'Lasers Surg Med',
'Lav Ist Anat Istol Patol Univ Studi Perugia',
'Learn Mem',
'Leg Med (Tokyo)',
'Leuk Lymphoma',
'Leuk Res',
'Life Sci',
'Life Sci [I]',
'Life Sci I',
'Life Sci Space Res',
'Lipids',
'Lipids Health Dis',
'Liver',
'Liver Int',
'Lung Cancer',
'Lupus',
'Lymphokine Cytokine Res',
'M S - Med Sci',
'M S Med Sci',
'MAbs',
'MAGMA',
'Magn Reson Imaging',
'Magn Reson Med',
'Mar Drugs',
'Matrix',
'Matrix Biol',
'Matrix Suppl',
'Mayo Clin Proc',
'MBio',
'Mech Ageing Dev',
'Mech Dev',
'Med Arh',
'Med Electron Microsc',
'Med Eng Phys',
'Med Hypotheses',
'Med J Aust',
'Med Microbiol Immunol (Berl)',
'Med Mol Morphol',
'Med Monatsschr Pharm',
'Med Parazitol (Mosk)',
'Med Pediatr Oncol',
'Med Sci Monit',
'Med Sci Res',
'Med Sci Sports Exerc',
'Mediators Inflamm',
'Medicina (B Aires)',
'Medicina Buenos Aires',
'Melanoma Res',
'Mem Inst Oswaldo Cruz',
'Mem Soc Endocrinol',
'Mem Tokyo Univ Agriculture',
'Metab Brain Dis',
'Metabolism',
'Metal Ions Biol Med',
'Methods',
'Methods Cell Biol',
'Methods Enzymol',
'Methods Mol Biol',
'Methods Mol Med',
'Methods Neurosci',
'Microb Ecol Health Dis',
'Microb Pathog',
'Microbes Infect',
'Microbiol Immunol',
'Microbiol Mol Biol Rev',
'Microbiol Rev',
'Microbiologica',
'Microbiology',
'Microbios',
'Microcirculation',
'Microsc Microanal',
'Microsc Res Tech',
'Microsurgery',
'Microvasc Res',
'Middle East Afr J Ophthalmol',
'Mie Med J',
'Mil Med',
'Miner Electrolyte Metab',
'Minerva Cardioangiol',
'Mitochondrion',
'MMWR Morb Mortal Wkly Rep',
'Mod Rheumatol',
'Mol Aspects Med',
'Mol Autism',
'Mol Biochem Parasitol',
'Mol Biol (Mosk)',
'Mol Biol Evol',
'Mol Biol Med',
'Mol Biol Rep',
'Mol Biosyst',
'Mol Biotechnol',
'Mol Brain',
'Mol Cancer',
'Mol Cancer Res',
'Mol Cancer Ther',
'Mol Carcinog',
'Mol Cell Biol Hum Dis Ser',
'Mol Cell Biol Res Commun',
'Mol Cell Differ',
'Mol Cell Endocrinol',
'Mol Cell Neurosci',
'Mol Cell Probes',
'Mol Cell Proteomics',
'Mol Cells',
'Mol Chem Neuropathol',
'Mol Ecol',
'Mol Endocrinol',
'Mol Gen Genet',
'Mol Genet Genomic Med',
'Mol Genet Genomics',
'Mol Genet Metab',
'Mol Genet Metab Rep',
'Mol Hum Reprod',
'Mol Imaging',
'Mol Imaging Biol',
'Mol Interv',
'Mol Med',
'Mol Med Rep',
'Mol Med Today',
'Mol Membr Biol',
'Mol Metab',
'Mol Microbiol',
'Mol Neurobiol',
'Mol Neurodegener',
'Mol Oncol',
'Mol Pain',
'Mol Pathol',
'Mol Pharm',
'Mol Pharmacol',
'Mol Phylogenet Evol',
'Mol Psychiatry',
'Mol Reprod Dev',
'Mol Syst Biol',
'Mol Ther',
'Mol Ther Methods Clin Dev',
'Monogr Dev Biol',
'Morphol Jahr',
'Mov Disord',
'mSystems',
'Mt Sinai J Med',
'Mucosal Immunol',
'Muscle Nerve',
'Mutagenesis',
'Mutat Res',
'Mycopathologia',
'N Engl J Med',
'N Z Med J',
'Nan Fang Yi Ke Da Xue Xue Bao',
'Nanotoxicology',
'Nat Cell Biol',
'Nat Chem Biol',
'Nat Commun',
'Nat Immunol',
'Nat Med',
'Nat Nanotechnol',
'Nat New Biol',
'Nat Protoc',
'Nat Rev Cancer',
'Nat Rev Drug Discov',
'Nat Rev Endocrinol',
'Nat Rev Genet',
'Nat Rev Immunol',
'Nat Rev Mol Cell Biol',
'Nat Rev Neurosci',
'Nat Struct Biol',
'Nat Struct Mol Biol',
'Natl Cancer Inst Monogr',
'Natl Inst Anim Health Q (Tokyo)',
'Naturwissenschaften',
'Naunyn Schmiedebergs Arch Exp Pathol Pharmakol',
'Naunyn Schmiedebergs Arch Pharmacol',
'Neonatology',
'Neoplasia',
'Neoplasma',
'Nephrol Dial Transplant',
'Nephron',
'Nephron Exp Nephrol',
'Nephron Physiol',
'Neural Dev',
'Neural Netw',
'Neural Plast',
'Neuro Endocrinol Lett',
'Neuro Oncol',
'Neurobiol Learn Mem',
'Neurobiology',
'Neurochem Int',
'Neurochem Pathol',
'Neurochem Res',
'Neurodegener Dis',
'Neurodegeneration',
'Neuroendocrinol Lett',
'Neuroendocrinology',
'Neurogastroenterol Motil',
'Neurogenetics',
'Neuroimage',
'Neuroimmunomodulation',
'Neuroinformatics',
'Neurol Med Chir (Tokyo)',
'Neurol Res',
'Neurology',
'Neuromolecular Med',
'Neuromuscul Disord',
'Neuron Glia Biol',
'Neuropathol Appl Neurobiol',
'Neuropediatrics',
'Neuropeptides',
'Neuropharmacology',
'Neuropsychobiology',
'Neuropsychopharmacology',
'Neuroreport',
'Neurosci Biobehav Rev',
'Neurosci Bull',
'Neurosci Commun (Houst)',
'Neurosci Res',
'Neurosci Res Commun',
'Neuroscientist',
'Neurosurg Focus',
'Neurosurgery',
'Neurotherapeutics',
'Neurotoxicol Teratol',
'Neurotoxicology',
'Neurourol Urodyn',
'New Biol',
'New Microbiol',
'News Physiol Sci',
'NIDA Res Monogr',
'Nihon Rinsho Meneki Gakkai Kaishi',
'Nippon Ika Daigaku Zasshi',
'Nippon Jinzo Gakkai Shi',
'Nippon Juigaku Zasshi',
'Nippon Kyobu Shikkan Gakkai Zasshi',
'Nippon Rai Gakkai Zasshi',
'Nippon Sanka Fujinka Gakkai Zasshi',
'Nippon Yakurigaku Zasshi',
'Nitric Oxide',
'NMR Biomed',
'Northwest Dent Res',
'Nouv Rev Fr Hematol',
'Novartis Found Symp',
'Nowotwory',
'Nucl Med Biol',
'Nucl Med Commun',
'Nucleic Acids Symp Ser (Oxf)',
'Nucleosides Nucleotides Nucleic Acids',
'Nucleus',
'Nutr Cancer',
'Nutr Clin Pract',
'Nutr Diabetes',
'Nutr Metab (Lond)',
'Nutr Metab Cardiovasc Dis',
'Nutr Neurosci',
'Nutr Res',
'Nutr Rev',
'Nutrition',
'Obes Res',
'Obes Rev',
'Obesity (Silver Spring)',
'Occup Med (Oxf)',
'Odontology',
'Okajimas Folia Anat Jpn',
'Oncogene Res',
'Oncogenesis',
'Oncoimmunology',
'Oncol Rep',
'Oncol Res',
'Oncology',
'Oncology Reports',
'Oncotarget',
'Ontogenez',
'Open Virol J',
'Ophthalmic Genet',
'Ophthalmic Res',
'Ophthalmol Clin North Am',
'Ophthalmology',
'Opt Express',
'Optom Vis Sci',
'Oral Dis',
'Oral Microbiol Immunol',
'Oral Oncol',
'Organogenesis',
'ORL J Otorhinolaryngol Relat Spec',
'Orphanet J Rare Dis',
'Orthod Craniofac Res',
'Osteoarthritis Cartilage',
'Osteoporos Int',
'Otol Neurotol',
'Otolaryngol Head Neck Surg',
'Oxf Surv Eukaryot Genes',
'PA Acad Sci',
'Paediatr Perinat Epidemiol',
'Pain',
'Pak J Biol Sci',
'Pancreas',
'Pancreatology',
'Parasite',
'Parasite Immunol',
'Parasitol Int',
'Parasitol Res',
'Parasitol Today',
'Parasitology',
'Parkinsonism Relat Disord',
'Parkinsons Dis',
'Part Fibre Toxicol',
'Pathobiol Aging Age Relat Dis',
'Pathobiology',
'Pathogenetics',
'Pathol Biol (Paris)',
'Pathol Eur',
'Pathol Immunopathol Res',
'Pathol Int',
'Pathol Oncol Res',
'Pathol Res Pract',
'Pathology',
'PCR Methods Appl',
'Pediatr Blood Cancer',
'Pediatr Cardiol',
'Pediatr Dermatol',
'Pediatr Dev Pathol',
'Pediatr Nephrol',
'Pediatr Neurol',
'Pediatr Pathol',
'Pediatr Pulmonol',
'Pediatr Res',
'Pediatr Surg Int',
'Pediatrics',
'PeerJ',
'Peptides',
'Percept Mot Skills',
'Perspect Assist Reprod',
'Perspect Dev Neurobiol',
'Pharm Acta Helv',
'Pharm Res',
'Pharmacogenet Genomics',
'Pharmacogenetics',
'Pharmacogenomics J',
'Pharmacol Biochem Behav',
'Pharmacol Res',
'Pharmacol Res Commun',
'Pharmacol Rev',
'Pharmacol Ther',
'Pharmacol Toxicol',
'Pharmacology',
'Pharmazie',
'Philos Trans R Soc Lond B Biol Sci',
'Photochem Photobiol',
'Photochem Photobiol Sci',
'Photodermatol',
'Photodermatol Photoimmunol Photomed',
'Phys Biol',
'Phys Med',
'Physiol Behav',
'Physiol Bohemoslov',
'Physiol Chem Phys Med NMR',
'Physiol Genomics',
'Physiol Psychol',
'Physiol Rep',
'Physiol Res',
'Physiol Rev',
'Physiol Zool',
'Physiology',
'Phytomedicine',
'Phytother Res',
'Pigment Cell Melanoma Res',
'Pituitary',
'Placenta',
'Planta Med',
'Plasmid',
'Plast Reconstr Surg',
'Platelets',
'PLoS Comput Biol',
'PLoS Curr',
'PLoS Med',
'PLoS Negl Trop Dis',
'PLoS Pathog',
'Pol J Pharmacol Pharm',
'Postepy Biochem',
'Postgrad Med J',
'PPAR Res',
'Preclinica',
'Prenat Diagn',
'Prim Sens Neuron',
'Princess Takamatsu Symp',
'Prion',
'Proc Am Thorac Soc',
'Proc Anim Care Panel',
'Proc Assoc Am Physicians',
'Proc Aust Assoc Anim Breeding Genet',
'Proc Chin Acad Med Sci Peking Union Med Coll',
'Proc Jpn Acad',
'Proc Louisiana Acad Sci',
'Proc Natl Sci Counc Repub China B',
'Proc Nutr Soc',
'Proc R Soc Edinb [Biol]',
'Proc R Soc Lond B Biol Sci',
'Proc Soc Exp Biol Med',
'Proc Univ Otago Med School, Dunedin, NZ',
'Proc West Pharmacol Soc',
'Proc Zool Soc (Bengal)',
'Prog Biophys Mol Biol',
'Prog Brain Res',
'Prog Clin Biol Res',
'Prog Exp Tumor Res',
'Prog Growth Factor Res',
'Prog Hematol',
'Prog Immunol',
'Prog Lipid Res',
'Prog Neurobiol',
'Prog Neuropsychopharmacol Biol Psychiatry',
'Prog Nucleic Acid Res Mol Biol',
'Prog Retin Eye Res',
'Prostaglandins Leukot Essent Fatty Acids',
'Prostaglandins Other Lipid Mediat',
'Prostate',
'Prostate Cancer Prostatic Dis',
'Protein Cell',
'Protein Eng',
'Protein Expr Purif',
'Protein Profile',
'Protein Sci',
'Proteins',
'Proteomics',
'Protoplasma',
'Psychiatr Genet',
'Psychiatry Clin Neurosci',
'Psychiatry Res',
'Psychobiology',
'Psychol Rec',
'Psychol Rep',
'Psychoneuroendocrinology',
'Psychopharmacologia',
'Psychopharmacology (Berl)',
'Psychosom Med',
'Public Health Rep',
'Pulm Circ',
'Purinergic Signal',
'Q J Exp Physiol',
'Q J Microsc Sci',
'Q J Stud Alcohol',
'Q Rev Biol',
'QJM',
'Quality Control Report',
'Radiat Environ Biophys',
'Radiat Oncol Investig',
'Radiat Res',
'Radiats Biol Radioecol',
'Radiology',
'Radiother Oncol',
'Rare Dis',
'Rec Med Vet',
'Recent Adv Microscopy Cells Tissues Organs',
'Recent Prog Horm Res',
'Recent Res Dev Lipids Res',
'Recent Results Cancer Res',
'Receptor',
'Receptors Channels',
'Redox Biol',
'Redox Rep',
'Reg Immunol',
'Regul Toxicol Pharmacol',
'Rejuvenation Res',
'Ren Physiol Biochem',
'Reprod Biol',
'Reprod Biol Endocrinol',
'Reprod Biomed Online',
'Reprod Domest Anim',
'Reprod Fertil Dev',
'Reprod Nutr Dev',
'Reprod Sci',
'Reprod Syst Sex Disord',
'Reprod Toxicol',
'Reproduction',
'Res Commun Chem Pathol Pharmacol',
'Res Commun Mol Pathol Pharmacol',
'Res Exp Med (Berl)',
'Res Immunol',
'Res Microbiol',
'Res Vet Sci',
'Res Virol',
'Respir Physiol',
'Respir Physiol Neurobiol',
'Respir Res',
'Restorative Neurol Neurosci',
'Results Probl Cell Differ',
'Retina',
'Retrovirology',
'Rev Diabet Stud',
'Rev Endocr Metab Disord',
'Rev Esp Fisiol',
'Rev Infect Dis',
'Rev Med Virol',
'Rev Neurosci',
'Rev Reprod',
'Rev Rhum Ed Fr',
'Rev Roum Med Intern',
'Rev Soc Bras Med Trop',
'Rev Suisse Zool',
'Rheumatol Int',
'Rheumatology (Oxford)',
'Rinsho Hoshasen',
'Risk Anal',
'RNA',
'RNA Biol',
'Roux''s Arch Dev Biol',
'Ryumachi',
'Sarcoma',
'Saudi J Ophthalmol',
'Saudi Med J',
'Scand Audiol Suppl',
'Scand J Clin Lab Invest',
'Scand J Clin Lab Invest Suppl',
'Scand J Gastroenterol',
'Scand J Haematol',
'Scand J Immunol',
'Scand J Infect Dis',
'Scand J Infect Dis Suppl',
'Scand J Plast Reconstr Surg Hand Surg',
'Scand J Rheumatol',
'Scand J Rheumatol Suppl',
'Scanning Microsc',
'Schizophr Bull',
'Schizophr Res',
'Sci Adv',
'Sci Aging Knowledge Environ',
'Sci Am',
'Sci China  B',
'Sci China C Life Sci',
'Sci China Life Sci',
'Sci China Ser C',
'Sci Signal',
'ScientificWorldJournal',
'Scientist',
'Semin Cancer Biol',
'Semin Cell Dev Biol',
'Semin Dev Biol',
'Semin Hematol',
'Semin Immunol',
'Semin Liver Dis',
'Semin Nephrol',
'Semin Neurosci',
'Semin Oncol',
'Semin Ophthalmol',
'Semin Perinatol',
'Semin Thromb Hemost',
'Semin Virol',
'Sex Dev',
'Sheng Li Xue Bao',
'Sheng Wu Hua Xue Yu Sheng Wu Wu Li Xue Bao (Shanghai)',
'Shock',
'Singapore Med J',
'Skelet Muscle',
'Skin Pharmacol',
'Skin Pharmacol Appl Skin Physiol',
'Skin Pharmacol Physiol',
'Small',
'Small GTPases',
'Soc Neurosci Symp',
'Somat Cell Mol Genet',
'Somatic Cell Genet',
'Somatosens Mot Res',
'Sov Genet',
'Spermatogenesis',
'Spinal Cord',
'Spine',
'Spine (Phila Pa 1976)',
'Springer Semin Immunopathol',
'Springerplus',
'Stem Cell Reports',
'Stem Cell Res',
'Stem Cell Res Ther',
'Stem Cell Rev',
'Stem Cells',
'Stem Cells (Dayt)',
'Stem Cells Dev',
'Stem Cells Int',
'Stem Cells Transl Med',
'Steroidologia',
'Steroids',
'Stress',
'Stroke',
'Structure',
'Subcell Biochem',
'Subst Alcohol Actions Misuse',
'Surg Endosc',
'Surg Neurol',
'Surg Radiol Anat',
'Surgery',
'Surv Immunol Res',
'Symp Zool Soc Lond',
'Synapse',
'Syst Biol',
'Technique',
'Technol Cancer Res Treat',
'Technol Health Care',
'Teratog Carcinog Mutagen',
'Theor Biol Med Model',
'Theranostics',
'Theriogenology',
'Thorac Cardiovasc Surg Rep',
'Thorax',
'Thromb Haemost',
'Thromb Res',
'Thymus',
'Thyroid',
'Thyroid Res',
'Tissue Antigens',
'Tissue Cell',
'Tissue Eng Part A',
'Tohoku J Exp Med',
'Tokai J Exp Clin Med',
'Toxic Rep Ser',
'Toxicol In Vitro',
'Toxicol Ind Health',
'Toxicol Lett',
'Toxicol Method',
'Toxicol Pathol',
'Toxicol Sci',
'Toxicology',
'Toxicon',
'Traffic',
'Traffic Inj Prev',
'Trans Am Clin Climatol Assoc',
'Trans N Y Acad Sci',
'Trans Orthop Res',
'Transfus Clin Biol',
'Transfusion',
'Transgenics',
'Transl Psychiatry',
'Transl Stroke Res',
'Transpl Immunol',
'Transplant Bull',
'Transplant Proc',
'Transplant Rev',
'Transplantation',
'Trend Cardiovasc Med',
'Trends Biochem Sci',
'Trends Biotechnol',
'Trends Cardiovasc Med',
'Trends Cell Biol',
'Trends Endocrinol Metab',
'Trends Genet',
'Trends Immunol',
'Trends Microbiol',
'Trends Mol Med',
'Trends Neurosci',
'Trends Parasitol',
'Trends Pharmacol Sci',
'Trop Gastroenterol',
'Trop Med Parasitol',
'Trophoblast Res',
'Tsitologiia',
'Tuber Lung Dis',
'Tumori',
'Tumour Biol',
'Ugeskr Laeger',
'Ultrasound Med Biol',
'Ultrastruct Pathol',
'Undersea Hyperb Med',
'Univ California Publ Zool',
'Ups J Med Sci',
'Urol Clin North Am',
'Urol Res',
'Urology',
'Vaccine',
'Vasc Cell',
'Vascul Pharmacol',
'Verh K Acad Geneeskd Belg',
'Vet Dermatol',
'Vet Hum Toxicol',
'Vet Immunol Immunopathol',
'Vet Microbiol',
'Vet Parasitol',
'Vet Pathol',
'Viral Immunol',
'Virchows Arch',
'Virchows Arch A Pathol Anat Histopathol',
'Virchows Arch A Pathol Pathol Anat',
'Virchows Arch B Cell Pathol Incl Mol Pathol',
'Virol J',
'Virology',
'Virus Genes',
'Virus Res',
'Vis Neurosci',
'Vision Res',
'Vitam Horm',
'Vopr Onkol',
'Wellcome Open Res',
'West J Med',
'Wiss Z Univ Halle [Math - Naturwiss]',
'World J Clin Cases',
'World J Gastroenterol',
'World J Orthop',
'Wound Repair Regen',
'Xenobiotica',
'Xenotransplantation',
'Yakugaku Zasshi',
'Yale J Biol Med',
'Yeast',
'Yi Chuan Xue Bao',
'Yi Chuan Xue Bao (Acta Genet Sinica)',
'Yi Chuan Xue Bao (Acta Genetica Sinica)',
'Yonsei Med J',
'Z Anat Entwicklungsgesch',
'Z Gastroenterol',
'Z Gerontol',
'Z Immunitatsforsch Immunobiol',
'Z Indukt Abstamm Vererbungsl',
'Z Kardiol',
'Z Kinderchir',
'Z Krebsforsch',
'Z Mensch Vererb Konst',
'Z Mikrosk Anat Forsch',
'Z Naturforsch [C]',
'Z Rheumatol',
'Z Vererbungsl',
'Z Versuchstierkd',
'Z Zellforsch Mikrosk Anat',
'Zbl Vet Med B',
'Zentralbl Allg Pathol',
'Zentralbl Bakteriol',
'Zentralbl Bakteriol [Orig]',
'Zentralbl Veterinarmed [B]',
'Zh Vyssh Nerv Deiat Im I P Pavlova',
'Zhongguo Fei Ai Za Zhi',
'Zhongguo Shi Yan Xue Ye Xue Za Zhi',
'Zhongguo Zhong Yao Za Zhi',
'Zhonghua Yi Xue Za Zhi',
'Zool Anzeiger Suppl',
'Zool Sci',
'Zoolog Mag',
'Zoolog Sci',
'Zschr Versuchstierk',
'Zygote',
'Int J Hypertens',
'Lancet Neurol',
'Biotechnol Bioeng',
'Cerebrospinal Fluid Res',
'Front Aging Neurosci',
'J Am Chem Soc',
'IBRO Reports'
)
;
EOSQL

