#!/bin/csh -f

#
# migrates bib_refs._referencetype_key
#


if ( ${?MGICONFIG} == 0 ) then
        setenv MGICONFIG /usr/local/mgi/live/mgiconfig
endif

source ${MGICONFIG}/master.config.csh

cd `dirname $0`

setenv LOG $0.log
rm -rf $LOG
touch $LOG
 
date | tee -a $LOG

cat - <<EOSQL | ${PG_DBUTILS}/bin/doisql.csh $0 | tee -a $LOG

update BIB_Refs r
set _ReferenceType_key = (select t._Term_key
        from VOC_Vocab v, VOC_Term t
        where v.name = 'Reference Type' and v._Vocab_key = t._Vocab_key 
        and t.term = 'Conference Proceedings/Abstracts')
where lower(r.pgs) like '%abstr%'
;

update BIB_Refs r
set _ReferenceType_key = (select t._Term_key
        from VOC_Vocab v, VOC_Term t
        where v.name = 'Reference Type' and v._Vocab_key = t._Vocab_key 
        and t.term = 'Conference Proceedings/Abstracts')
where lower(r.title) like '%abstract%'
;

update BIB_Refs r
set _ReferenceType_key = (select t._Term_key
        from VOC_Vocab v, VOC_Term t
        where v.name = 'Reference Type' and v._Vocab_key = t._Vocab_key 
        and t.term = 'MGI Data Load')
where r.authors like 'Mouse Genome Informatics%'
and r.journal is null
;

update BIB_Refs r
set _ReferenceType_key = (select t._Term_key
        from VOC_Vocab v, VOC_Term t
        where v.name = 'Reference Type' and v._Vocab_key = t._Vocab_key 
        and t.term = 'MGI Data Load')
where r.title in (
'Mammalian Orthology Load',
'Protein SuperFamily Classification Load',      
'HCOP Orthology Load',  
'Allen Brain Atlas [Internet] database Load',   
'MouseFuncLoad',
'Wikipedia Gene Summary Load',
'Mouse Genome Informatics Computational Sequence to Gene Associations for FANTOM2 data'
)
;

update BIB_Refs r
set _ReferenceType_key = (select t._Term_key
        from VOC_Vocab v, VOC_Term t
        where v.name = 'Reference Type' and v._Vocab_key = t._Vocab_key 
        and t.term = 'MGI Curation Record')
where r.title in (
'Cancer Gene Census',					
'Gene Ontology data from EBI',					
'Annotation inferences using phylogenetic trees',					
'Annotations generated by GO interontology links',					
'Adult Mouse Anatomical Dictionary',					
'Nomenclature rule change to delete hyphens and parentheses from mouse locus symbols',					
'MGI/HUGO Nomenclature Homology Determination',					
'Integrating Computationally assembled mouse transcript sequences (NIA Mouse Gene Index) with the Mouse Genome Informatics (MGI) Database',					
'LocusLink Collaboration',					
'Images Obtained from the Mouse Locus Catalog',					
'Mouse Genome Database Curtorial Assignment of Images to Database Objects',					
'Images obtained from the Mouse Mutant Resource',					
'Images obtained from JAXmedia',					
'Additional strain, gene, and allele synonyms obtained from The Jackson Laboratory Genetics Resources',					
'Curated associations of genes in MGI and UniProt sequence records',					
'Obtaining and Loading Genome Assembly Coordinates from Ensembl Annotations',					
'Mouse Contig Sequence-to-Marker Association Load',					
'Obtaining and loading genome assembly coordinates from NCBI annotations',					
'Automatic sequence to marker association based on spliced alignmemt',					
'Obtaining and Loading TreeFam Gene Family Annotations',					
'Gene Ontology Annotation by the MGI Curatorial Staff',					
'Gene Ontology Annotation by electronic association of SwissProt Keywords with GO terms',					
'Function or Process or Component Unknown following Literature Review',					
'Rat to Mouse ISO GO annotation transfer',					
'Human to Mouse ISO GO annotation transfer',					
'RIKEN Data Curation in Mouse Genome Informatics',					
'T31 Radiation Hybrid Data Curation in Mouse Genome Informatics',					
'Mouse Genome Informatics Computational Sequence to Gene Associations',					
'MGC Data curation in Mouse Genome Informatics',					
'Chromosome assignment of mouse genes using the Mouse Genome Sequencing Consortium (MGSC) assembly and the ENSEMBL Database',					
'Data Curation Using Mouse Genome Assembly',					
'Curation of the correct associations between MGI and Ensembl genes that have one to many relationships',					
'MGI Sequence Curation Reference',					
'Mouse Synonym Curation',					
'Mouse Genome Informatics Orthology Assignments',					
'FANTOM2 Data Curation in Mouse Genome Informatics',					
'Mapping assignment of mouse microRNAs',					
'Creating and loading NCBI genomic sequence to MGI gene associations',					
'Mouse Genome Sequence Project Annotation',					
'Strain Synonym Annotation by the Mouse Tumor Biology (MTB) Database Curatorial Staff',					
'GenBank Record Derived Information',					
'Gene Ontology data from RGD',					
'Mouse Olfactory Receptor Genes:  Reconciliation of multiple data collections against the public genome assembly',					
'Recombinase Mice Artemis',					
'Histone Genes: Associate Sequences and Biological information with the appropriate Genes.'					
)
;
EOSQL

