#!/bin/csh -f

setenv MIGRATIONDIR	/home/lec/db/mgidbmigration/ASSEMBLY

#setenv VOCLOAD       /usr/local/mgi/live/dataload/vocload/runSimpleFullLoadNoArchive.sh
setenv VOCLOAD       /home/lec/loads/vocload/runSimpleFullLoadNoArchive.sh
#setenv SEQMARKER	/usr/local/mgi/live/dbutils/seqcacheload/seqmarker.csh
setenv SEQMARKER	/home/lec/loads/seqcacheload/seqmarker.csh

# new (JSAM) schema configured to talk to the JSAM database
#setenv newmgddb /usr/local/mgi/live/dbutils/mgd
setenv newmgddb /home/lec/db
setenv newmgddbschema ${newmgddb}/mgddbschema
setenv newmgddbperms ${newmgddb}/mgddbperms

setenv CREATEDBY        1001
setenv SCHEMA_TAG	mgddbschema-10-0-0
setenv PUBLIC_VERSION	"MGI 3.1"
setenv PRODUCT_NAME	MGD

source ${newmgddbschema}/Configuration

