#!/bin/csh -f

setenv MIGRATIONDIR	/home/lec/db/mgidbmigration/MGI3.11

#setenv MRKREFLOAD	/usr/local/mgi/live/dbutils/mrkrefload/mrkref.sh
setenv MRKREFLOAD	/home/lec/loads/mrkrefload-maint6300/mrkref.sh

# new schema configured to talk to the MGI 3.11 database
#setenv newmgddb /usr/local/mgi/live/dbutils/mgd
setenv newmgddb /home/lec/db/mgi3.11
setenv newmgddbschema ${newmgddb}/mgddbschema
setenv newmgddbperms ${newmgddb}/mgddbperms

setenv CREATEDBY        1001
setenv SCHEMA_TAG	mgddbschema-3-1-1
setenv PUBLIC_VERSION	"MGI 3.11"
setenv PRODUCT_NAME	MGD

source ${newmgddbschema}/Configuration

