#!/bin/csh -f

setenv DBUTILITIESDIR	/usr/local/mgi/dbutils/mgidbutilities
setenv PYTHONPATH       /usr/local/mgi/lib/python

setenv VOCLOAD /usr/local/mgi/dataload/vocload

setenv newmgddb /usr/local/mgi/dbutils/mgd
#setenv newmgddb /home/lec/db/mgi2.96
setenv newmgddbschema ${newmgddb}/mgddbschema
setenv newmgddbperms ${newmgddb}/mgddbperms

setenv CREATEDBY mgd_dbo

source ${newmgddbschema}/Configuration

setenv DSQUERY ${DBSERVER}
setenv MGD ${DBNAME}
