#!/bin/csh -f

setenv SYBASE /opt/sybase
setenv DBSERVER $1
setenv DATABASE $2
setenv DBO mgd_dbo
setenv PASSWORD $SYBASE/admin/.mgd_dbo_password

set sql = /tmp/$$.sql

cat > $sql << EOSQL

use $DATABASE
go

grant all on ACC_Accession to progs
go

grant all on ACC_AccessionMax to progs
go

grant all on ACC_AccessionReference to progs
go

grant all on ALL_Allele to progs
go

grant all on ALL_Allele_Mutation to progs
go

grant all on ALL_Inheritance_Mode to progs
go

grant all on ALL_Molecular_Mutation to progs
go

grant all on ALL_Molecular_Note to progs
go

grant all on ALL_Note to progs
go

grant all on ALL_Synonym to progs
go

grant all on ALL_Type to progs
go

grant all on BIB_Books to progs
go

grant all on BIB_Notes to progs
go

grant all on BIB_Refs to progs
go

grant all on BIB_ReviewStatus to progs
go

grant all on CRS_Cross to progs
go

grant all on GXD_AllelePair to progs
go

grant all on GXD_Antibody to progs
go

grant all on GXD_AntibodyAlias to progs
go

grant all on GXD_AntibodyClass to progs
go

grant all on GXD_AntibodyMarker to progs
go

grant all on GXD_AntibodySpecies to progs
go

grant all on GXD_AntibodyPrep to progs
go

grant all on GXD_AntibodyType to progs
go

grant all on GXD_Antigen to progs
go

grant all on GXD_Assay to progs
go

grant all on GXD_AssayNote to progs
go

grant all on GXD_AssayType to progs
go

grant all on GXD_EmbeddingMethod to progs
go

grant all on GXD_Expression to progs
go

grant all on GXD_FixationMethod to progs
go

grant all on GXD_GelBand to progs
go

grant all on GXD_GelControl to progs
go

grant all on GXD_GelLane to progs
go

grant all on GXD_GelLaneStructure to progs
go

grant all on GXD_GelRNAType to progs
go

grant all on GXD_GelRow to progs
go

grant all on GXD_GelUnits to progs
go

grant all on GXD_Genotype to progs
go

grant all on GXD_ISResultStructure to progs
go

grant all on GXD_InSituResult to progs
go

grant all on GXD_InSituResultImage to progs
go

grant all on GXD_Index to progs
go

grant all on GXD_Index_Stages to progs
go

grant all on GXD_Label to progs
go

grant all on GXD_LabelCoverage to progs
go

grant all on GXD_Pattern to progs
go

grant all on GXD_ProbePrep to progs
go

grant all on GXD_ProbeSense to progs
go

grant all on GXD_Secondary to progs
go

grant all on GXD_Specimen to progs
go

grant all on GXD_Strength to progs
go

grant all on GXD_Structure to progs
go

grant all on GXD_StructureClosure to progs
go

grant all on GXD_StructureName to progs
go

grant all on GXD_TheilerStage to progs
go

grant all on GXD_VisualizationMethod to progs
go

grant all on HMD_Assay to progs
go

grant all on HMD_Class to progs
go

grant all on HMD_Homology to progs
go

grant all on HMD_Homology_Assay to progs
go

grant all on HMD_Homology_Marker to progs
go

grant all on HMD_Notes to progs
go

grant all on IMG_FieldType to progs
go

grant all on IMG_Image to progs
go

grant all on IMG_ImageNote to progs
go

grant all on IMG_ImagePane to progs
go

grant all on MLC_Lock_edit to progs
go

grant all on MLC_Marker_edit to progs
go

grant all on MLC_Reference_edit to progs
go

grant all on MLC_Text_edit to progs
go

grant all on MLD_Assay_Types to progs
go

grant all on MLD_Concordance to progs
go

grant all on MLD_Distance to progs
go

grant all on MLD_Expt_Marker to progs
go

grant all on MLD_Expt_Notes to progs
go

grant all on MLD_Expts to progs
go

grant all on MLD_FISH to progs
go

grant all on MLD_FISH_Region to progs
go

grant references on MLD_Hybrid to progs
go

grant insert on MLD_Hybrid to progs
go

grant all on MLD_ISRegion to progs
go

grant all on MLD_InSitu to progs
go

grant all on MLD_MC2point to progs
go

grant all on MLD_MCDataList to progs
go

grant all on MLD_Marker to progs
go

grant all on MLD_Matrix to progs
go

grant all on MLD_Notes to progs
go

grant all on MLD_PhysMap to progs
go

grant all on MLD_RI to progs
go

grant all on MLD_RI2Point to progs
go

grant all on MLD_RIData to progs
go

grant all on MLD_Statistics to progs
go

grant all on MRK_Alias to progs
go

grant all on MRK_Anchors to progs
go

grant all on MRK_Chromosome to progs
go

grant all on MRK_Class to progs
go

grant all on MRK_Classes to progs
go

grant all on MRK_Current to progs
go

grant all on MRK_Event to progs
go

grant all on MRK_EventReason to progs
go

grant all on MRK_History to progs
go

grant all on MRK_Label to progs
go

grant all on MRK_Marker to progs
go

grant all on MRK_Notes to progs
go

grant all on MRK_Offset to progs
go

grant all on MRK_Other to progs
go

grant all on MRK_Reference to progs
go

grant all on MRK_Species to progs
go

grant all on MRK_Status to progs
go

grant all on MRK_Types to progs
go

grant all on PRB_Alias to progs
go

grant all on PRB_Allele to progs
go

grant all on PRB_Allele_Strain to progs
go

grant all on PRB_Marker to progs
go

grant all on PRB_Notes to progs
go

grant all on PRB_Probe to progs
go

grant all on PRB_RFLV to progs
go

grant all on PRB_Ref_Notes to progs
go

grant all on PRB_Reference to progs
go

grant all on PRB_Source to progs
go

grant all on PRB_Strain to progs
go

grant all on PRB_Strain_Marker to progs
go

grant all on PRB_Tissue to progs
go

grant all on PRB_Vector_Types to progs
go

grant all on RI_RISet to progs
go

grant execute on MGI_resetSequenceNum to progs
go

grant execute on MLC_transfer to progs
go

grant execute on MRK_copyHistory to progs
go

grant execute on MRK_mergeWithdrawal to progs
go

grant execute on MRK_alleleWithdrawal to progs
go

grant execute on MRK_splitWithdrawal to progs
go

grant execute on MRK_alleleWithdrawal to progs
go

grant execute on PRB_mergeTissue to progs
go

grant execute on PRB_mergeStandardTissue to progs
go

grant execute on PRB_insertReference to progs
go

grant execute on MRK_insertHistory to progs
go

grant execute on MRK_breakpointSplit to progs
go

grant execute on MRK_addChromosome to progs
go

grant execute on MRK_reloadReference to progs
go

grant execute on ACC_resetMax to progs
go

grant execute on ACC_assignMGI to progs
go

grant execute on ACC_assignJ to progs
go

grant execute on ACCRef_insert to progs
go

grant execute on ACC_insert to progs
go

grant execute on ACC_insert_bySpecies to progs
go

grant execute on ACCRef_process to progs
go

grant execute on ALL_convertAllele to progs
go

grant execute on ALL_insertAllele to progs
go

grant execute on ALL_mergeAllele to progs
go

grant execute on GXD_loadCacheAll to progs
go

grant execute on IMG_setPDO to progs
go

grant execute on GXD_SetStructDescPrintName to progs
go

grant execute on GXD_ComputePrintNamesFrom to progs
go

grant execute on GXD_SetPreferredName to progs
go

checkpoint
go

EOSQL

cat $PASSWORD | isql -S$DBSERVER -U$DBO -e -i $sql
rm $sql
