#!/bin/csh -f

setenv SYBASE /opt/sybase
setenv DBSERVER $1
setenv DATABASE $2
setenv DBO mgd_dbo
setenv PASSWORD $SYBASE/admin/.mgd_dbo_password

set scripts = $SYBASE/admin
set sql = /tmp/$$.sql

cat > $sql << EOSQL

use $DATABASE
go

grant all on ACC_Accession to editors
go

grant all on ACC_AccessionMax to editors
go

grant all on ACC_AccessionReference to editors
go

grant all on ALL_Allele to editors
go

grant all on ALL_Allele_Mutation to editors
go

grant all on ALL_Inheritance_Mode to cml
go

grant all on ALL_Molecular_Mutation to cml
go

grant all on ALL_Molecular_Note to editors
go

grant all on ALL_Note to editors
go

grant all on ALL_Synonym to editors
go

grant all on ALL_Type to cml
go

grant all on BIB_Books to editors
go

grant all on BIB_Notes to editors
go

grant all on BIB_Refs to editors
go

grant all on BIB_ReviewStatus to jeo, neb
go

grant all on CRS_Cross to dbradt, neb, plg
go

grant all on GXD_AllelePair to dab, dph, ijm
go

grant all on GXD_Antibody to dab, dph, ijm
go

grant all on GXD_AntibodyAlias to dab, dph, ijm
go

grant all on GXD_AntibodyClass to dab, dph, ijm
go

grant all on GXD_AntibodyMarker to dab, dph, ijm
go

grant all on GXD_AntibodyPrep to dab, dph, ijm
go

grant all on GXD_AntibodySpecies to dab, dph, ijm
go

grant all on GXD_AntibodyType to dab, dph, ijm
go

grant all on GXD_Antigen to dab, dph, ijm
go

grant all on GXD_Assay to dab, dph, ijm
go

grant all on GXD_AssayNote to dab, dph, ijm
go

grant all on GXD_AssayType to dab, dph, ijm
go

grant all on GXD_EmbeddingMethod to dab, dph, ijm
go

grant all on GXD_Expression to dab, dph, ijm
go

grant all on GXD_FixationMethod to dab, dph, ijm
go

grant all on GXD_GelBand to dab, dph, ijm
go

grant all on GXD_GelControl to dab, dph, ijm
go

grant all on GXD_GelLane to dab, dph, ijm
go

grant all on GXD_GelLaneStructure to dab, dph, ijm
go

grant all on GXD_GelRNAType to dab, dph, ijm
go

grant all on GXD_GelRow to dab, dph, ijm
go

grant all on GXD_GelUnits to dab, dph, ijm
go

grant all on GXD_Genotype to dab, dph, ijm
go

grant all on GXD_ISResultStructure to dab, dph, ijm
go

grant all on GXD_InSituResult to dab, dph, ijm
go

grant all on GXD_InSituResultImage to dab, dph, ijm
go

grant all on GXD_Index to dab, dph, ijm
go

grant all on GXD_Index_Stages to dab, dph, ijm
go

grant all on GXD_Label to dab, dph, ijm
go

grant all on GXD_LabelCoverage to dab, dph, ijm
go

grant all on GXD_Pattern to dab, dph, ijm
go

grant all on GXD_ProbePrep to dab, dph, ijm
go

grant all on GXD_ProbeSense to dab, dph, ijm
go

grant all on GXD_Secondary to dab, dph, ijm
go

grant all on GXD_Specimen to dab, dph, ijm
go

grant all on GXD_Strength to dab, dph, ijm
go

grant all on GXD_Structure to dab, dph, ijm
go

grant all on GXD_StructureClosure to dab, dph, ijm
go

grant all on GXD_StructureName to dab, dph, ijm
go

grant all on GXD_TheilerStage to dab, dph, ijm
go

grant all on GXD_VisualizationMethod to dab, dph, ijm
go

grant all on HMD_Assay to cml, dbradt, djr, dph, jblake, ljm, lmm, plg, rmb, sr, tc
go

grant all on HMD_Class to cml, dbradt, djr, dph, jblake, ljm, lmm, plg, rmb, sr, tc
go

grant all on HMD_Homology to cml, dbradt, djr, dph, jblake, ljm, lmm, plg, rmb, sr, tc
go

grant all on HMD_Homology_Assay to cml, dbradt, djr, dph, jblake, ljm, lmm, plg, rmb, sr, tc
go

grant all on HMD_Homology_Marker to cml, dbradt, djr, dph, jblake, ljm, lmm, plg, rmb, sr, tc
go

grant all on HMD_Notes to cml, dbradt, djr, dph, jblake, ljm, lmm, plg, rmb, sr, tc
go

grant all on IMG_FieldType to dab, dph, ijm
go

grant all on IMG_Image to dab, dph, ijm
go

grant all on IMG_ImageNote to dab, dph, ijm
go

grant all on IMG_ImagePane to dab, dph, ijm
go

grant all on MLC_Lock_edit to cml, dbradt, dph, jblake, lmm, rmb, sr, tc, wjb
go

grant all on MLC_Marker_edit to cml, dbradt, dph, jblake, lmm, rmb, sr, tc, wjb
go

grant all on MLC_Reference_edit to cml, dbradt, dph, jblake, lmm, rmb, sr, tc, wjb
go

grant all on MLC_Text_edit to cml, dbradt, dph, jblake, lmm, rmb, sr, tc, wjb
go

grant all on MLD_Assay_Types to dbradt, neb, plg, sr
go

grant all on MLD_Concordance to dbradt, neb, plg, sr
go

grant all on MLD_Distance to dbradt, neb, plg, sr
go

grant all on MLD_Expt_Marker to dbradt, neb, plg, sr
go

grant all on MLD_Expt_Notes to dbradt, neb, plg, sr
go

grant all on MLD_Expts to dbradt, neb, plg, sr
go

grant all on MLD_FISH to dbradt, neb, plg, sr
go

grant all on MLD_FISH_Region to dbradt, neb, plg, sr
go

grant references on MLD_Hybrid to dbradt, neb, plg, sr
go

grant insert on MLD_Hybrid to dbradt, neb, plg, sr
go

grant all on MLD_ISRegion to dbradt, neb, plg, sr
go

grant all on MLD_InSitu to dbradt, neb, plg, sr
go

grant all on MLD_MC2point to dbradt, neb, plg, sr
go

grant all on MLD_MCDataList to dbradt, neb, plg, sr
go

grant all on MLD_Marker to dbradt, neb, plg, sr
go

grant all on MLD_Matrix to dbradt, neb, plg, sr
go

grant all on MLD_Notes to dbradt, neb, plg, sr
go

grant all on MLD_PhysMap to dbradt, neb, plg, sr
go

grant all on MLD_RI to dbradt, neb, plg, sr
go

grant all on MLD_RI2Point to dbradt, neb, plg, sr
go

grant all on MLD_RIData to dbradt, neb, plg, sr
go

grant all on MLD_Statistics to dbradt, neb, plg, sr
go

grant all on MRK_Alias to cml, dab, dbradt, djr, dph, ljm, lmm, neb, rmb, sr, tc
go

grant all on MRK_Anchors to cml, dab, dbradt, djr, dph, ljm, lmm, neb, rmb, sr, tc
go

grant all on MRK_Chromosome to cml, dab, dbradt, djr, dph, ljm, lmm, neb, plg, rmb, sr, tc
go

grant all on MRK_Class to cml, dab, dbradt, djr, dph, jblake, ljm, lmm, neb, rmb, sr, tc, wjb
go

grant all on MRK_Classes to cml, dab, dbradt, djr, dph, jblake, ljm, lmm, neb, rmb, sr, tc, wjb
go

grant all on MRK_Current to cml, dab, dbradt, djr, dph, ljm, lmm, neb, rmb, sr, tc
go

grant all on MRK_EventReason to ljm, lmm
go

grant all on MRK_History to cml, dab, djr, dph, ljm, lmm, neb, rmb, tc
go

grant all on MRK_Marker to cml, dab, dbradt, djr, dph, jblake, ljm, lmm, neb, plg, rmb, sr, tc
go

grant all on MRK_Notes to cml, dab, dbradt, djr, dph, ljm, lmm, neb, plg, rmb, sr, tc
go

grant all on MRK_Offset to cml, dab, dbradt, djr, dph, ljm, lmm, mlp, neb, plg, rmb, sr, tc
go

grant all on MRK_Other to editors
go

grant all on MRK_Reference to cml, dab, dbradt, djr, dph, jblake, ljm, lmm, neb, rmb, sr, tc
go

grant all on MRK_Species to cml, dab, dbradt, djr, dph, ljm, lmm, neb, plg, rmb, sr, tc
go

grant all on PRB_Alias to dbradt, djr, dph, mlp, neb, plg, rmb, sr
go

grant all on PRB_Allele to dbradt, djr, dph, mlp, neb, plg, rmb, sr
go

grant all on PRB_Allele_Strain to dbradt, djr, dph, mlp, neb, plg, rmb, sr
go

grant all on PRB_Marker to dbradt, djr, dph, mlp, neb, plg, rmb, sr
go

grant all on PRB_Notes to dbradt, djr, dph, mlp, neb, plg, rmb, sr
go

grant all on PRB_Probe to dbradt, djr, dph, mlp, neb, plg, rmb, sr
go

grant all on PRB_RFLV to dab, dbradt, djr, dph, ijm, mlp, neb, plg, rmb, sr
go

grant all on PRB_Ref_Notes to dbradt, djr, dph, mlp, neb, plg, rmb, sr
go

grant all on PRB_Reference to dab, dbradt, djr, dph, ijm, mlp, neb, plg, rmb, sr
go

grant all on PRB_Source to dab, dbradt, djr, dph, ijm, mlp, neb, plg, rmb, sr
go

grant all on PRB_Strain to dab, mlp
go

grant insert on PRB_Strain to editors
go

grant all on PRB_Strain_Marker to dbradt, djr, lhg, ljm, mlp, neb, sr
go

grant all on PRB_Tissue to dab, dbradt, djr, dph, ijm, mlp, neb, plg, rmb, sr
go

grant all on PRB_Vector_Types to dab, dbradt, djr, dph, ijm, mlp, neb, plg, rmb, sr
go

grant all on RI_RISet to plg, sr
go

grant execute on MGI_resetSequenceNum to editors
go

grant execute on MLC_transfer to cml, dbradt, dph, jblake, lmm, rmb, sr, tc, wjb
go

grant execute on MRK_copyHistory to djr, ljm, rmb
go

grant execute on MRK_mergeWithdrawal to djr, ljm, rmb
go

grant execute on MRK_alleleWithdrawal to djr, ljm, rmb
go

grant execute on MRK_splitWithdrawal to djr, ljm, rmb
go

grant execute on MRK_alleleWithdrawal to djr, ljm, rmb
go

grant execute on PRB_mergeTissue to editors
go

grant execute on PRB_mergeStandardTissue to editors
go

grant execute on PRB_insertReference to editors
go

grant execute on MRK_insertHistory to djr, ljm, rmb
go

grant execute on MRK_breakpointSplit to djr, ljm, rmb
go

grant execute on MRK_addChromosome to editors
go

grant execute on MRK_reloadReference to editors
go

grant execute on ACC_resetMax to editors
go

grant execute on ACC_assignMGI to editors
go

grant execute on ACC_assignJ to editors
go

grant execute on ACCRef_insert to editors
go

grant execute on ACC_insert to editors
go

grant execute on ACC_insert_bySpecies to editors
go

grant execute on ACCRef_process to editors
go

grant execute on ALL_convertAllele to djr, ljm, rmb
go

grant execute on ALL_insertAllele to djr, ljm, rmb
go

grant execute on ALL_mergeAllele to editors
go

grant execute on GXD_loadCacheAll to editors
go

grant execute on IMG_setPDO to editors
go

grant execute on GXD_SetStructDescPrintName to editors
go

grant execute on GXD_ComputePrintNamesFrom to editors
go

grant execute on GXD_SetPreferredName to editors
go

checkpoint
go

EOSQL

cat $PASSWORD | isql -S$DBSERVER -U$DBO -e -i $sql
rm $sql
