#!/bin/csh -f

#setenv MIGRATIONDIR	/usr/local/mgi/3.2/dbutils/mgidbmigration/MPR
setenv MIGRATIONDIR	/home/lec/db/mgidbmigration/MPR

setenv VOCLOAD		/usr/local/mgi/3.2/dataload/vocload

#setenv VOCSIMPLELOAD    /usr/local/mgi/3.2/dataload/vocload-3-1-0-2/runSimpleFullLoadNoArchive.sh
setenv VOCSIMPLELOAD    /home/lec/loads/vocload/runSimpleFullLoadNoArchive.sh

#setenv ANNOTLOAD	/usr/local/mgi/3.2/dataload/annotload
setenv ANNOTLOAD	/home/lec/loads/annotload-mpr

#setenv ASSOCLOAD        /usr/local/mgi/3.2/dataload/vocassociationload
setenv ASSOCLOAD        /home/lec/loads/vocassociationload

#setenv NOTELOAD	/usr/local/mgi/3.2/dataload/noteload
setenv NOTELOAD		/home/lec/loads/noteload

#setenv ALLLABELLOAD	/usr/local/mgi/3.2/dbutils/alllabelload
setenv ALLLABELLOAD	/home/lec/loads/alllabelload

#setenv MRKREFLOAD	/usr/local/mgi/3.2/dbutils/mrkrefload
setenv MRKREFLOAD	/home/lec/loads/mrkrefload-mpr

#setenv newmgddb /usr/local/mgi/3.2/dbutils/mgd
setenv newmgddb /home/lec/db/mpr
setenv newmgddbschema ${newmgddb}/mgddbschema
setenv newmgddbperms ${newmgddb}/mgddbperms

#setenv newradardb /usr/local/mgi/3.2/dbutils/radar
setenv newradardb /home/lec/db/mpr
setenv newradardbschema ${newradardb}/radardbschema
setenv newradardbperms ${newradardb}/radardbperms

setenv SCHEMA_TAG       mgddbschema-3-2-0
setenv RADARSCHEMA_TAG  radardbschema-3-2-0
setenv CREATEDBY	1000

source ${newradardbschema}/Configuration
setenv RADARDB $DBNAME

source ${newmgddbschema}/Configuration

