#!/bin/csh -f

setenv DBUTILITIESDIR	/usr/local/mgi/dbutils/mgidbutilities

setenv VOCLOAD          /usr/local/mgi/dataload/vocload/runSimpleFullLoadNoArchive.sh
setenv PYTHONPATH       ${PYTHONPATH}:${VOCLOAD}

#setenv newmgddb /usr/local/mgi/dbutils/mgd
setenv newmgddb /home/lec/db
setenv newmgddbschema ${newmgddb}/mgddbschema
setenv newmgddbperms ${newmgddb}/mgddbperms

#setenv newnomendb //usr/local/mgi/dbutils/nomen
setenv newnomendb /home/lec/db
setenv newnomendbschema ${newmgddb}/nomendbschema
setenv newnomendbperms ${newmgddb}/nomendbperms
setenv NOMEN nomen_lec

setenv CREATEDBY	"dbo"
setenv SCHEMA_TAG	mgddbschema-7-1-0

source ${newmgddbschema}/Configuration

