#!/bin/csh -f

# Production settings
#
#setenv MGIDBUTILS	/usr/local/mgi/live/dbutils/mgidbutilities
#setenv MGDDBSCHEMA	/usr/local/mgi/live/dbutils/mgd/mgddbschema
#setenv MGDDBPERMS	/usr/local/mgi/live/dbutils/mgd/mgddbperms
#setenv RADARDBSCHEMA	/usr/local/mgi/live/dbutils/radar/radardbschema
#setenv RADARDBPERMS	/usr/local/mgi/live/dbutils/radar/radardbperms
#setenv RADARDBUTILS	/usr/local/mgi/live/dbutils/radardbutilities

# Development settings
#
setenv MGIDBUTILS	/usr/local/mgi/3.01/dbutils/mgidbutilities
setenv MGDDBSCHEMA	/usr/local/mgi/3.01/dbutils/mgd/mgddbschema
setenv MGDDBPERMS	/usr/local/mgi/3.01/dbutils/mgd/mgddbperms
setenv RADARDBSCHEMA	/usr/local/mgi/3.01/dbutils/radar/radardbschema
setenv RADARDBPERMS	/usr/local/mgi/3.01/dbutils/radar/radardbperms
setenv RADARDBUTILS	/usr/local/mgi/3.01/dbutils/radardbutilities

setenv JOBSTART_CSH	${RADARDBUTILS}/bin/startJobStream.csh
setenv JOBEND_CSH	${RADARDBUTILS}/bin/endJobStream.csh

setenv MGD_BACKUP	/shire/sybase/mgd.backup
setenv RADAR_BACKUP	/shire/sybase/radar.backup

setenv CREATEDBY	1000
