#!/bin/csh -f

# Production settings
#
#setenv MGDDBSCHEMA	/usr/local/mgi/live/dbutils/mgd/mgddbschema
#setenv MGDDBPERMS	/usr/local/mgi/live/dbutils/mgd/mgddbperms
#setenv RADARDBSCHEMA	/usr/local/mgi/live/dbutils/radar/radardbschema
#setenv RADARDBPERMS	/usr/local/mgi/live/dbutils/radar/radardbperms
#setenv RADARDBUTILS	/usr/local/mgi/live/dbutils/radardbutilities

# Development settings
#
setenv MGDDBSCHEMA	/usr/local/mgi/3.01/dbutils/mgd/mgddbschema
setenv MGDDBPERMS	/usr/local/mgi/3.01/dbutils/mgd/mgddbperms
setenv RADARDBSCHEMA	/usr/local/mgi/3.01/dbutils/radar/radardbschema
setenv RADARDBPERMS	/usr/local/mgi/3.01/dbutils/radar/radardbperms
setenv RADARDBUTILS	/usr/local/mgi/3.01/dbutils/radardbutilities

setenv CREATEDBY	1000
