#!/bin/csh -f

#setenv MIGRATIONDIR	/usr/local/mgi/live/dbutils/mgidbmigration/TR7018
setenv MIGRATIONDIR	/home/lec/db/mgidbmigration/TR7018

setenv VOCSIMPLELOAD    /usr/local/mgi/live/dataload/vocload/runSimpleFullLoadNoArchive.sh
setenv NOTELOAD		/usr/local/mgi/live/dataload/noteload/mginoteload.py
setenv NOTEMODE		preview
setenv DATAFILE         journal.rpt
setenv NOTETYPE         "Journal Copyright"
setenv OBJECTTYPE       "Vocabulary Term"

#setenv newmgddb /usr/local/mgi/live/dbutils/mgd
setenv newmgddb /home/lec/db/fantom3
setenv newmgddbschema ${newmgddb}/mgddbschema
setenv newmgddbperms ${newmgddb}/mgddbperms

setenv SCHEMA_TAG       mgddbschema-3-3-0
setenv CREATEDBY	1000

source ${newmgddbschema}/Configuration

