#!/bin/csh -f

if ( ${?MGICONFIG} == 0 ) then
	setenv MGICONFIG /home/lec/build36/mgiconfig
endif

source ${MGICONFIG}/master.config.csh

#setenv oldsnpdb /usr/local/mgi/live/dbutils/snp_migration
setenv oldsnpdb /home/sc/snp2/dbutils/snp_migration
setenv oldsnpdbschema ${oldsnpdb}/snpdbschema


