#!/bin/csh -f

#setenv MIGRATIONDIR	/usr/local/mgi/3.2/dbutils/mgidbmigration/MPR
setenv MIGRATIONDIR	/home/lec/db/mgidbmigration/MGI3.22

#setenv newmgddb /usr/local/mgi/3.2/dbutils/mgd
setenv newmgddb /home/lec/db/maint6840
setenv newmgddbschema ${newmgddb}/mgddbschema
setenv newmgddbperms ${newmgddb}/mgddbperms

setenv PUBLIC_VERSION   "MGI 3.22"

source ${newmgddbschema}/Configuration

